// templates/mod.rs
//
// All HTML generated by Rust functions returning String.
// No template engine — zero overhead, zero mismatches.
//
// Security: every user-supplied string passes through escape_html() before
// insertion.  Template literals are trusted Rust strings only.

use crate::config::CONFIG;
use crate::models::*;
use crate::utils::{files::format_file_size, sanitize::escape_html};

// ─── Shared JS injected once per page ────────────────────────────────────────

const TOGGLE_SCRIPT: &str = r#"<script>
function togglePostForm() {
  var wrap = document.getElementById('post-form-wrap');
  var btn  = document.querySelector('.post-toggle-btn');
  if (!wrap) return;
  var opening = wrap.style.display === 'none';
  wrap.style.display = opening ? 'block' : 'none';
  if (btn) btn.classList.toggle('active', opening);
  if (opening) {
    var first = wrap.querySelector('input[type="text"], textarea');
    if (first) first.focus();
  }
}
function appendReply(id) {
  var wrap = document.getElementById('post-form-wrap');
  if (wrap && wrap.style.display === 'none') togglePostForm();
  var ta = document.getElementById('reply-body');
  if (ta) { ta.value += '>>' + id + '\n'; ta.focus(); }
  return false;
}
function expandMedia(preview) {
  var container = preview.closest('.file-container');
  var expanded  = container.querySelector('.media-expanded');
  var closeBtn  = container.querySelector('.media-close-btn');
  if (expanded.tagName === 'IMG' && expanded.dataset.src) {
    expanded.src = expanded.dataset.src;
  }
  preview.style.display  = 'none';
  expanded.style.display = 'block';
  closeBtn.style.display = 'inline-flex';
  if (expanded.tagName === 'VIDEO') {
    expanded.play().catch(function(){});
  }
}
function collapseMedia(btn) {
  var container = btn.closest('.file-container');
  var expanded  = container.querySelector('.media-expanded');
  var preview   = container.querySelector('.media-preview');
  if (expanded.tagName === 'VIDEO') {
    expanded.pause();
    expanded.currentTime = 0;
  }
  expanded.style.display = 'none';
  preview.style.display  = 'block';
  btn.style.display      = 'none';
}
</script>"#;
use chrono::{TimeZone, Utc};

// ─── Timestamp helpers ────────────────────────────────────────────────────────

fn fmt_ts(ts: i64) -> String {
    match Utc.timestamp_opt(ts, 0) {
        chrono::LocalResult::Single(dt) => dt.format("%Y-%m-%d %H:%M:%S UTC").to_string(),
        _ => "unknown".to_string(),
    }
}

fn fmt_ts_short(ts: i64) -> String {
    match Utc.timestamp_opt(ts, 0) {
        chrono::LocalResult::Single(dt) => dt.format("%m/%d/%y(%a)%H:%M:%S").to_string(),
        _ => "?".to_string(),
    }
}

// ─── Base layout ─────────────────────────────────────────────────────────────

fn base_layout(title: &str, board_short: Option<&str>, body: &str, csrf_token: &str, boards: &[Board]) -> String {
    let board_links: String = boards
        .iter()
        .map(|b| format!(
            r#"[<a href="/{s}/catalog">{s}</a>]"#,
            s = escape_html(&b.short_name)
        ))
        .collect::<Vec<_>>()
        .join(" ");

    let search_bar = if let Some(b) = board_short {
        format!(
            r#"<form class="search-form" method="GET" action="/{b}/search">
<input type="text" name="q" placeholder="search /{b}/…" maxlength="64">
<button type="submit">go</button>
</form>"#,
            b = escape_html(b)
        )
    } else {
        String::new()
    };

    // Sticky catalog bar shown when browsing a specific board
    let catalog_bar = if let Some(b) = board_short {
        format!(
            r#"<div class="catalog-bar">
  <a class="catalog-bar-link" href="/{b}/catalog">[ /{b}/ catalog ]</a>
  <span class="catalog-bar-sep">|</span>
  <a class="catalog-bar-link" href="/{b}/">[ /{b}/ index ]</a>
</div>"#,
            b = escape_html(b)
        )
    } else {
        String::new()
    };

    format!(
        r#"<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="referrer" content="no-referrer">
<title>{title}</title>
<link rel="stylesheet" href="/static/style.css">
</head>
<body>
<header class="site-header">
  <a class="home-btn" href="/">&#8962; Home</a>
  <nav class="board-list">
    {board_links}
    [<a href="/admin">Admin</a>]
  </nav>
  <div class="header-search">{search_bar}</div>
</header>
{catalog_bar}
<main>
{body}
</main>
<footer class="site-footer">
  <p>{forum_name} &mdash; <a href="/">home</a></p>
</footer>
<input type="hidden" id="csrf_global" value="{csrf_token}">
</body>
</html>"#,
        title       = escape_html(title),
        board_links = board_links,
        search_bar  = search_bar,
        catalog_bar = catalog_bar,
        forum_name  = escape_html(&CONFIG.forum_name),
        body        = body,
        csrf_token  = escape_html(csrf_token),
    )
}

// ─── Index (board list) ───────────────────────────────────────────────────────

pub fn index_page(board_stats: &[crate::models::BoardStats], csrf_token: &str) -> String {
    // Build a plain boards list for the nav bar
    let all_boards: Vec<Board> = board_stats.iter().map(|s| s.board.clone()).collect();

    let sfw:  Vec<&crate::models::BoardStats> = board_stats.iter().filter(|s| !s.board.nsfw).collect();
    let nsfw: Vec<&crate::models::BoardStats> = board_stats.iter().filter(|s|  s.board.nsfw).collect();

    fn board_cards(list: &[&crate::models::BoardStats]) -> String {
        list.iter().map(|s| {
            let b = &s.board;
            let nsfw_badge = if b.nsfw { r#"<span class="nsfw-badge">NSFW</span>"# } else { "" };
            let thread_word = if s.thread_count == 1 { "thread" } else { "threads" };
            format!(
                r#"<a class="board-card" href="/{sh}/catalog">
  <div class="board-card-short">/{sh}/</div>
  <div class="board-card-name">{n}{nsfw}</div>
  <div class="board-card-desc">{d}</div>
  <div class="board-card-stats">{tc} {tw}</div>
</a>"#,
                sh   = escape_html(&b.short_name),
                n    = escape_html(&b.name),
                nsfw = nsfw_badge,
                d    = escape_html(&b.description),
                tc   = s.thread_count,
                tw   = thread_word,
            )
        }).collect()
    }

    let sfw_sec = if !sfw.is_empty() {
        format!("<div class=\"index-section\"><h2 class=\"index-section-title\">// Boards</h2><div class=\"board-cards\">{}</div></div>", board_cards(&sfw))
    } else { String::new() };

    let nsfw_sec = if !nsfw.is_empty() {
        format!("<div class=\"index-section\"><h2 class=\"index-section-title\">// Adult Boards <span class=\"nsfw-badge\">NSFW</span></h2><div class=\"board-cards\">{}</div></div>", board_cards(&nsfw))
    } else { String::new() };

    let empty = if board_stats.is_empty() {
        "<p class=\"index-empty\">no boards yet — admin must create boards first.</p>"
    } else { "" };

    let body = format!(
        r#"<div class="index-hero">
<h1 class="index-title">[ {name} ]</h1>
<p class="index-subtitle">select board to proceed</p>
</div>
{sfw}{nsfw}{empty}"#,
        name = escape_html(&CONFIG.forum_name),
        sfw = sfw_sec, nsfw = nsfw_sec, empty = empty,
    );

    base_layout(&CONFIG.forum_name, None, &body, csrf_token, &all_boards)
}

// ─── Board index ──────────────────────────────────────────────────────────────

pub fn board_page(
    board: &Board,
    summaries: &[ThreadSummary],
    pagination: &Pagination,
    csrf_token: &str,
    boards: &[Board],
    is_admin: bool,
) -> String {
    let mut body = String::new();

    // Visible admin toolbar — appears whenever an admin is logged in
    if is_admin {
        body.push_str(&format!(
            r#"<div class="admin-toolbar">
<span class="admin-toolbar-label">&#9632; ADMIN</span>
<a href="/admin/panel">panel</a>
<form method="POST" action="/admin/logout" style="display:inline">
<input type="hidden" name="_csrf" value="{csrf}">
<button type="submit" class="admin-toolbar-btn">logout</button>
</form>
</div>"#,
            csrf = escape_html(csrf_token),
        ));
    }

    body.push_str(&format!(
        r#"<div class="board-header"><h1>/{short}/  — {name}</h1><p class="board-desc">{desc}</p></div>"#,
        short = escape_html(&board.short_name),
        name  = escape_html(&board.name),
        desc  = escape_html(&board.description),
    ));

    body.push_str(&format!(
        r#"<div class="post-toggle-bar centered">
  <button class="post-toggle-btn" onclick="togglePostForm()">[ Start a New Thread ]</button>
</div>
<div class="post-form-wrap" id="post-form-wrap" style="display:none">
  {}
</div>"#,
        new_thread_form(&board.short_name, csrf_token),
    ));

    for summary in summaries {
        body.push_str(&render_thread_summary(summary, &board.short_name, csrf_token, is_admin));
    }

    body.push_str(&render_pagination(pagination, &format!("/{}/", board.short_name)));

    body.push_str(TOGGLE_SCRIPT);

    base_layout(
        &format!("/{}/", board.short_name),
        Some(&board.short_name),
        &body,
        csrf_token,
        boards,
    )
}

fn new_thread_form(board_short: &str, csrf_token: &str) -> String {
    let image_mb = crate::config::CONFIG.max_image_size / 1024 / 1024;
    let video_mb = crate::config::CONFIG.max_video_size / 1024 / 1024;
    format!(
        r#"<div class="post-form-container">
<div class="post-form-title">[ new thread ]</div>
<form class="post-form" method="POST" action="/{board}/" enctype="multipart/form-data">
  <input type="hidden" name="_csrf" value="{csrf}">
  <table>
    <tr><td>name</td>
        <td><input type="text" name="name" placeholder="Anonymous" maxlength="64"></td></tr>
    <tr><td>subject</td>
        <td><input type="text" name="subject" maxlength="128">
            <button type="submit">post thread</button></td></tr>
    <tr><td>body</td>
        <td><textarea name="body" rows="5" maxlength="4096" required></textarea></td></tr>
    <tr><td>file</td>
        <td><input type="file" name="file" accept="image/jpeg,image/png,image/gif,image/webp,video/mp4,video/webm">
            <span style="font-size:0.72rem;color:var(--text-dim)">jpg/png/gif/webp · max {image_mb} MiB &nbsp;|&nbsp; mp4/webm · max {video_mb} MiB</span></td></tr>
    <tr><td>del token</td>
        <td><input type="text" name="deletion_token" placeholder="password to delete" maxlength="64"></td></tr>
  </table>
</form>
</div>"#,
        board     = escape_html(board_short),
        csrf      = escape_html(csrf_token),
        image_mb  = image_mb,
        video_mb  = video_mb,
    )
}

fn render_thread_summary(summary: &ThreadSummary, board_short: &str, csrf_token: &str, is_admin: bool) -> String {
    let t = &summary.thread;
    let mut html = String::new();

    let sticky_label = if t.sticky { r#"<span class="tag sticky">STICKY</span> "# } else { "" };
    let locked_label = if t.locked { r#"<span class="tag locked">LOCKED</span> "# } else { "" };

    html.push_str(&format!(
        r#"<div class="thread" id="t{tid}">
<div class="op post" id="p{op_id}">"#,
        tid   = t.id,
        op_id = t.op_id.unwrap_or(0),
    ));

    if let (Some(_file), Some(thumb)) = (&t.op_file, &t.op_thumb) {
        html.push_str(&format!(
            r#"<div class="file-container"><a href="/{board}/thread/{tid}"><img class="thumb" src="/uploads/{th}" loading="lazy" alt="image"></a></div>"#,
            board = escape_html(board_short),
            tid   = t.id,
            th    = escape_html(thumb),
        ));
    }

    html.push_str(&format!(
        r#"<div class="post-meta">
{sticky}{locked}
<strong class="name">{name}</strong>
<span class="post-time">{time}</span>
<a class="post-num" href="/{board}/thread/{tid}">No.{op_id}</a>
</div>"#,
        sticky = sticky_label,
        locked = locked_label,
        name   = escape_html(t.op_name.as_deref().unwrap_or("Anonymous")),
        time   = fmt_ts_short(t.created_at),
        board  = escape_html(board_short),
        tid    = t.id,
        op_id  = t.op_id.unwrap_or(0),
    ));

    if let Some(subject) = &t.subject {
        html.push_str(&format!(
            r#"<div class="subject"><a href="/{b}/thread/{tid}"><strong>{s}</strong></a></div>"#,
            b   = escape_html(board_short),
            tid = t.id,
            s   = escape_html(subject),
        ));
    }

    if let Some(body) = &t.op_body {
        let truncated = if body.len() > 300 {
            format!(
                r#"{} <a href="/{b}/thread/{tid}">…[Read more]</a>"#,
                escape_html(&body[..300]),
                b   = escape_html(board_short),
                tid = t.id,
            )
        } else {
            escape_html(body)
        };
        html.push_str(&format!(r#"<div class="post-body">{}</div>"#, truncated));
    }

    html.push_str(&format!(
        r#"<div class="thread-footer">
<a href="/{board}/thread/{tid}">[reply] ({n} {word})</a>"#,
        board = escape_html(board_short),
        tid   = t.id,
        n     = t.reply_count,
        word  = if t.reply_count == 1 { "reply" } else { "replies" },
    ));

    // Admin: delete thread button on board index (thread page uses the toolbar instead)
    if is_admin {
        html.push_str(&format!(
            r#" <form method="POST" action="/admin/thread/delete" style="display:inline">
<input type="hidden" name="_csrf"      value="{csrf}">
<input type="hidden" name="thread_id"  value="{tid}">
<input type="hidden" name="board"      value="{board}">
<button type="submit" class="admin-del-btn"
        onclick="return confirm('Delete thread No.{tid} and all its posts?')">&#x2715; del thread</button>
</form>"#,
            csrf  = escape_html(csrf_token),
            tid   = t.id,
            board = escape_html(board_short),
        ));
    }

    html.push_str("</div>\n</div>");

    if summary.omitted > 0 {
        html.push_str(&format!(
            r#"<div class="omitted">{} posts omitted. <a href="/{b}/thread/{tid}">view thread</a></div>"#,
            summary.omitted,
            b   = escape_html(board_short),
            tid = t.id,
        ));
    }

    for post in &summary.preview_posts {
        html.push_str(&render_post(post, board_short, csrf_token, false, is_admin));
    }

    html.push_str("<hr class=\"thread-sep\">");
    html
}

// ─── Thread page ──────────────────────────────────────────────────────────────

pub fn thread_page(
    board: &Board,
    thread: &Thread,
    posts: &[Post],
    csrf_token: &str,
    boards: &[Board],
    is_admin: bool,
) -> String {
    let mut body = String::new();

    // Visible admin toolbar
    if is_admin {
        body.push_str(&format!(
            r#"<div class="admin-toolbar">
<span class="admin-toolbar-label">&#9632; ADMIN</span>
<a href="/admin/panel">panel</a>
<form method="POST" action="/admin/thread/delete" style="display:inline">
<input type="hidden" name="_csrf" value="{csrf}">
<input type="hidden" name="thread_id" value="{tid}">
<input type="hidden" name="board" value="{board}">
<button type="submit" class="admin-toolbar-btn admin-toolbar-danger"
        onclick="return confirm('Delete this entire thread and all its posts?')">&#x2715; delete thread</button>
</form>
<form method="POST" action="/admin/logout" style="display:inline">
<input type="hidden" name="_csrf" value="{csrf}">
<button type="submit" class="admin-toolbar-btn">logout</button>
</form>
</div>"#,
            csrf  = escape_html(csrf_token),
            tid   = thread.id,
            board = escape_html(&board.short_name),
        ));
    }

    let locked_notice = if thread.locked {
        r#"<div class="notice locked-notice">this thread is locked — no new replies allowed</div>"#
    } else { "" };

    body.push_str(&format!(
        r#"<div class="board-header">
<a href="/{s}/">[ return ]</a> | <a href="/{s}/catalog">[ catalog ]</a>
</div>
"#,
        s = escape_html(&board.short_name),
    ));
    body.push_str(locked_notice);

    for post in posts {
        body.push_str(&render_post(post, &board.short_name, csrf_token, true, is_admin));
    }

    if !thread.locked {
        body.push_str(&format!(
            r#"<div class="post-toggle-bar reply">
  <button class="post-toggle-btn" onclick="togglePostForm()">[ Reply ]</button>
</div>
<div class="post-form-wrap" id="post-form-wrap" style="display:none">
  {}
</div>"#,
            reply_form(&board.short_name, thread.id, csrf_token),
        ));
    }

    body.push_str(TOGGLE_SCRIPT);

    base_layout(
        &format!("/{}/  {}", board.short_name, thread.subject.as_deref().unwrap_or("thread")),
        Some(&board.short_name),
        &body,
        csrf_token,
        boards,
    )
}

pub fn render_post(post: &Post, board_short: &str, csrf_token: &str, show_delete: bool, is_admin: bool) -> String {
    let tripcode_html = post.tripcode.as_ref()
        .map(|t| format!(r#"<span class="tripcode">!{}</span>"#, escape_html(t)))
        .unwrap_or_default();

    let op_class = if post.is_op { " op" } else { " reply" };

    let mut html = format!(
        r##"<div class="post{op_class}" id="p{id}">
<div class="post-meta">
<strong class="name">{name}</strong>{tripcode}
<span class="post-time">{time}</span>
<a class="post-num" href="#p{id}" onclick="appendReply({id})">No.{id}</a>
</div>"##,
        op_class = op_class,
        id       = post.id,
        name     = escape_html(&post.name),
        tripcode = tripcode_html,
        time     = fmt_ts_short(post.created_at),
    );

    if let Some(subject) = &post.subject {
        html.push_str(&format!(
            r#"<div class="subject"><strong>{}</strong></div>"#,
            escape_html(subject)
        ));
    }

    // Image / Video
    if let (Some(file), Some(thumb)) = (&post.file_path, &post.thumb_path) {
        let size_str = post.file_size.map(format_file_size).unwrap_or_default();
        let name_str = post.file_name.as_deref().unwrap_or("file");
        let is_video = post.mime_type.as_deref().map(|m| m.starts_with("video/")).unwrap_or(false);
        let mime     = post.mime_type.as_deref().unwrap_or("video/mp4");

        if is_video {
            html.push_str(&format!(
                r#"<div class="file-container">
<div class="file-info">
  <a href="/uploads/{f}">{orig}</a> ({sz})
  <button class="media-close-btn" onclick="collapseMedia(this)" style="display:none">&#x2715; close</button>
</div>
<div class="media-preview" onclick="expandMedia(this)" title="click to play">
  <img class="thumb" src="/uploads/{th}" loading="lazy" alt="video thumbnail">
  <div class="media-expand-overlay">&#9654;</div>
</div>
<video class="media-expanded" src="/uploads/{f}" controls preload="none"
       type="{mime}" style="display:none"></video>
</div>"#,
                f    = escape_html(file),
                th   = escape_html(thumb),
                orig = escape_html(name_str),
                sz   = escape_html(&size_str),
                mime = escape_html(mime),
            ));
        } else {
            html.push_str(&format!(
                r#"<div class="file-container">
<div class="file-info">
  <a href="/uploads/{f}">{orig}</a> ({sz})
  <button class="media-close-btn" onclick="collapseMedia(this)" style="display:none">&#x2715; close</button>
</div>
<div class="media-preview" onclick="expandMedia(this)" title="click to expand">
  <img class="thumb" src="/uploads/{th}" loading="lazy" alt="image">
  <div class="media-expand-overlay">&#x2922;</div>
</div>
<img class="media-expanded" src="" data-src="/uploads/{f}" style="display:none"
     alt="image">
</div>"#,
                f    = escape_html(file),
                th   = escape_html(thumb),
                orig = escape_html(name_str),
                sz   = escape_html(&size_str),
            ));
        }
    }

    // Post body (pre-rendered, sanitised HTML)
    html.push_str(&format!(r#"<div class="post-body">{}</div>"#, post.body_html));

    // User delete form (only on thread pages where show_delete=true)
    if show_delete {
        html.push_str(&format!(
            r#"<div class="post-controls">
<form class="delete-form" method="POST" action="/delete">
<input type="hidden" name="_csrf"    value="{csrf}">
<input type="hidden" name="post_id"  value="{pid}">
<input type="hidden" name="board"    value="{board}">
<input type="text"   name="deletion_token" placeholder="del token" maxlength="64" size="12">
<button type="submit" class="del-btn">del</button>
</form>
</div>"#,
            csrf  = escape_html(csrf_token),
            pid   = post.id,
            board = escape_html(board_short),
        ));
    }

    // Admin delete button — shown whenever admin is logged in, regardless of page
    if is_admin {
        html.push_str(&format!(
            r#"<div class="post-controls admin-post-controls">
<form method="POST" action="/admin/post/delete">
<input type="hidden" name="_csrf"   value="{csrf}">
<input type="hidden" name="post_id" value="{pid}">
<input type="hidden" name="board"   value="{board}">
<button type="submit" class="admin-del-btn"
        onclick="return confirm('Admin delete post No.{pid}?')">&#x2715; admin del</button>
</form>
</div>"#,
            csrf  = escape_html(csrf_token),
            pid   = post.id,
            board = escape_html(board_short),
        ));
    }

    html.push_str("</div>\n");
    html
}

fn reply_form(board_short: &str, thread_id: i64, csrf_token: &str) -> String {
    let image_mb = crate::config::CONFIG.max_image_size / 1024 / 1024;
    let video_mb = crate::config::CONFIG.max_video_size / 1024 / 1024;
    format!(
        r#"<div class="post-form-container reply-form-container">
<div class="post-form-title">[ reply to thread ]</div>
<form class="post-form" method="POST" action="/{board}/thread/{tid}" enctype="multipart/form-data">
  <input type="hidden" name="_csrf" value="{csrf}">
  <table>
    <tr><td>name</td>
        <td><input type="text" name="name" placeholder="Anonymous" maxlength="64"></td></tr>
    <tr><td>body</td>
        <td><textarea id="reply-body" name="body" rows="4" maxlength="4096" required></textarea>
            <button type="submit">post reply</button></td></tr>
    <tr><td>file</td>
        <td><input type="file" name="file" accept="image/jpeg,image/png,image/gif,image/webp,video/mp4,video/webm">
            <span style="font-size:0.72rem;color:var(--text-dim)">jpg/png/gif/webp · max {image_mb} MiB &nbsp;|&nbsp; mp4/webm · max {video_mb} MiB</span></td></tr>
    <tr><td>del token</td>
        <td><input type="text" name="deletion_token" placeholder="password to delete" maxlength="64"></td></tr>
  </table>
</form>
</div>"#,
        board    = escape_html(board_short),
        tid      = thread_id,
        csrf     = escape_html(csrf_token),
        image_mb = image_mb,
        video_mb = video_mb,
    )
}

// ─── Catalog page ─────────────────────────────────────────────────────────────

pub fn catalog_page(board: &Board, threads: &[Thread], csrf_token: &str, boards: &[Board]) -> String {
    let bs = escape_html(&board.short_name);
    let bn = escape_html(&board.name);

    let mut body = format!(
        r#"<div class="board-header">
  <h1>/{bs}/  — {bn} — catalog</h1>
  <p class="board-desc">{desc}</p>
</div>
<div class="post-toggle-bar centered">
  <button class="post-toggle-btn" onclick="togglePostForm()">[ Start a New Thread ]</button>
</div>
<div class="post-form-wrap" id="post-form-wrap" style="display:none">
  {form}
</div>
<div class="catalog-grid">"#,
        bs   = bs,
        bn   = bn,
        desc = escape_html(&board.description),
        form = new_thread_form(&board.short_name, csrf_token),
    );

    for t in threads {
        let thumb_html = if let Some(th) = &t.op_thumb {
            format!(r#"<img class="catalog-thumb" src="/uploads/{}" loading="lazy" alt="">"#, escape_html(th))
        } else {
            r#"<div class="catalog-no-image">no img</div>"#.to_string()
        };

        let subject = t.subject.as_deref().unwrap_or_else(|| t.op_body.as_deref().unwrap_or(""));
        let preview: String = subject.chars().take(80).collect();

        body.push_str(&format!(
            r#"<div class="catalog-item{sticky}">
<a href="/{board}/thread/{tid}">
{thumb}
<div class="catalog-info">
<span class="catalog-replies">{replies}R</span>
<p class="catalog-subject">{subj}</p>
</div>
</a>
</div>"#,
            sticky  = if t.sticky { " sticky" } else { "" },
            board   = escape_html(&board.short_name),
            tid     = t.id,
            thumb   = thumb_html,
            replies = t.reply_count,
            subj    = escape_html(&preview),
        ));
    }

    body.push_str("</div>");
    body.push_str(TOGGLE_SCRIPT);
    base_layout(
        &format!("/{}/  catalog", board.short_name),
        Some(&board.short_name),
        &body,
        csrf_token,
        boards,
    )
}

// ─── Search results ───────────────────────────────────────────────────────────

pub fn search_page(
    board: &Board,
    query: &str,
    posts: &[Post],
    pagination: &Pagination,
    csrf_token: &str,
    boards: &[Board],
) -> String {
    let mut body = format!(
        r#"<div class="page-box">
<h2 style="color:var(--green-pale);font-size:0.9rem;margin-bottom:8px">search: "{}" in /{}/</h2>
<form method="GET" action="/{}/search">
  <input type="text" name="q" value="{}" maxlength="64" style="background:var(--bg-input);border:1px solid var(--border);color:var(--green-pale);padding:4px 8px;font-family:var(--font)">
  <button type="submit">search</button>
</form>"#,
        escape_html(query),
        escape_html(&board.short_name),
        escape_html(&board.short_name),
        escape_html(query),
    );

    if posts.is_empty() {
        body.push_str(r#"<p style="color:var(--text-dim);margin-top:8px">no results found.</p>"#);
    } else {
        body.push_str(&format!(r#"<p style="color:var(--text-dim);font-size:0.8rem;margin-top:6px">{} result(s)</p>"#, pagination.total));
        for post in posts {
            body.push_str(&render_post(post, &board.short_name, csrf_token, false, false));
        }
        body.push_str(&render_pagination(
            pagination,
            &format!("/{}/search?q={}", board.short_name, urlencoding_simple(query)),
        ));
    }

    body.push_str("</div>");
    base_layout(
        &format!("search — /{}/", board.short_name),
        Some(&board.short_name),
        &body,
        csrf_token,
        boards,
    )
}

// ─── Admin pages ──────────────────────────────────────────────────────────────

pub fn admin_login_page(error: Option<&str>, csrf_token: &str, boards: &[Board]) -> String {
    let err_html = error
        .map(|e| format!(r#"<div class="error">{}</div>"#, escape_html(e)))
        .unwrap_or_default();

    let body = format!(
        r#"<div class="page-box admin-login">
<h2>[ admin login ]</h2>
{err}
<form method="POST" action="/admin/login">
<input type="hidden" name="_csrf" value="{csrf}">
<table>
<tr><td>username</td><td><input type="text" name="username" autofocus required autocomplete="username"></td></tr>
<tr><td>password</td><td><input type="password" name="password" required autocomplete="current-password"></td></tr>
<tr><td></td><td><button type="submit">authenticate</button></td></tr>
</table>
</form>
</div>"#,
        err  = err_html,
        csrf = escape_html(csrf_token),
    );
    base_layout("admin login", None, &body, csrf_token, boards)
}

pub fn admin_panel_page(boards: &[Board], bans: &[Ban], filters: &[WordFilter], csrf_token: &str) -> String {
    let mut board_rows = String::new();
    for b in boards {
        board_rows.push_str(&format!(
            r#"<tr>
<td>/{}/</td><td>{}</td><td>{}</td>
<td>
<form method="POST" action="/admin/board/delete" style="display:inline">
<input type="hidden" name="_csrf" value="{csrf}">
<input type="hidden" name="board_id" value="{id}">
<button type="submit" class="btn-danger" onclick="return confirm('delete /{short}/ and all content?')">delete</button>
</form>
</td>
</tr>"#,
            escape_html(&b.short_name),
            escape_html(&b.name),
            escape_html(&b.description),
            csrf  = escape_html(csrf_token),
            id    = b.id,
            short = escape_html(&b.short_name),
        ));
    }

    let mut ban_rows = String::new();
    for ban in bans {
        let expires = ban.expires_at.map(fmt_ts).unwrap_or_else(|| "permanent".to_string());
        ban_rows.push_str(&format!(
            r#"<tr>
<td class="ip-hash">{}</td><td>{}</td><td>{}</td>
<td>
<form method="POST" action="/admin/ban/remove" style="display:inline">
<input type="hidden" name="_csrf" value="{csrf}">
<input type="hidden" name="ban_id" value="{id}">
<button type="submit">lift</button>
</form>
</td>
</tr>"#,
            escape_html(&ban.ip_hash[..16]),
            escape_html(ban.reason.as_deref().unwrap_or("")),
            escape_html(&expires),
            csrf = escape_html(csrf_token),
            id   = ban.id,
        ));
    }

    let mut filter_rows = String::new();
    for f in filters {
        filter_rows.push_str(&format!(
            r#"<tr>
<td>{}</td><td>{}</td>
<td>
<form method="POST" action="/admin/filter/remove" style="display:inline">
<input type="hidden" name="_csrf" value="{csrf}">
<input type="hidden" name="filter_id" value="{id}">
<button type="submit">remove</button>
</form>
</td>
</tr>"#,
            escape_html(&f.pattern),
            escape_html(&f.replacement),
            csrf = escape_html(csrf_token),
            id   = f.id,
        ));
    }

    let body = format!(
        r#"<div class="admin-panel">
<h1>[ admin panel ]</h1>
<form method="POST" action="/admin/logout">
<input type="hidden" name="_csrf" value="{csrf}">
<button type="submit">logout</button>
</form>

<section class="admin-section">
<h2>// boards</h2>
<table class="admin-table">
<thead><tr><th>board</th><th>name</th><th>description</th><th>action</th></tr></thead>
<tbody>{board_rows}</tbody>
</table>
<h3>create board</h3>
<form method="POST" action="/admin/board/create">
<input type="hidden" name="_csrf" value="{csrf}">
<input type="text" name="short_name" placeholder="short (e.g. tech)" maxlength="8" required>
<input type="text" name="name" placeholder="full name" maxlength="64" required>
<input type="text" name="description" placeholder="description" maxlength="256">
<label style="color:var(--text-dim);font-size:0.8rem"><input type="checkbox" name="nsfw" value="1"> NSFW</label>
<button type="submit">create</button>
</form>
</section>

<section class="admin-section">
<h2>// active bans</h2>
<table class="admin-table">
<thead><tr><th>ip hash (partial)</th><th>reason</th><th>expires</th><th>action</th></tr></thead>
<tbody>{ban_rows}</tbody>
</table>
<h3>add ban</h3>
<form method="POST" action="/admin/ban/add">
<input type="hidden" name="_csrf" value="{csrf}">
<input type="text" name="ip_hash" placeholder="ip hash" required>
<input type="text" name="reason" placeholder="reason">
<input type="text" name="duration_hours" placeholder="hours (blank=perm)" style="width:120px">
<button type="submit">ban</button>
</form>
</section>

<section class="admin-section">
<h2>// word filters</h2>
<table class="admin-table">
<thead><tr><th>pattern</th><th>replacement</th><th>action</th></tr></thead>
<tbody>{filter_rows}</tbody>
</table>
<h3>add filter</h3>
<form method="POST" action="/admin/filter/add">
<input type="hidden" name="_csrf" value="{csrf}">
<input type="text" name="pattern" placeholder="pattern to match" required>
<input type="text" name="replacement" placeholder="replace with">
<button type="submit">add</button>
</form>
</section>
</div>"#,
        csrf        = escape_html(csrf_token),
        board_rows  = board_rows,
        ban_rows    = ban_rows,
        filter_rows = filter_rows,
    );

    base_layout("admin panel", None, &body, csrf_token, boards)
}

// ─── Error page ───────────────────────────────────────────────────────────────

pub fn error_page(code: u16, message: &str) -> String {
    format!(
        r#"<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Error {code}</title>
<link rel="stylesheet" href="/static/style.css">
</head>
<body>
<div class="page-box error-page">
<h1>error {code}</h1>
<p>{message}</p>
<p><a href="/">return home</a></p>
</div>
</body>
</html>"#,
        code    = code,
        message = escape_html(message),
    )
}

// ─── Pagination helper ────────────────────────────────────────────────────────

fn render_pagination(p: &Pagination, base_url: &str) -> String {
    if p.total_pages() <= 1 { return String::new(); }
    let sep = if base_url.contains('?') { "&" } else { "?" };
    let mut html = String::from(r#"<div class="pagination">"#);

    if p.has_prev() {
        html.push_str(&format!(r#"<a href="{}{sep}page={}">[prev]</a> "#, base_url, p.page - 1, sep = sep));
    }
    html.push_str(&format!("page {} / {}", p.page, p.total_pages()));
    if p.has_next() {
        html.push_str(&format!(r#" <a href="{}{sep}page={}">[next]</a>"#, base_url, p.page + 1, sep = sep));
    }

    html.push_str("</div>");
    html
}

fn urlencoding_simple(s: &str) -> String {
    s.chars()
        .map(|c| match c {
            'A'..='Z' | 'a'..='z' | '0'..='9' | '-' | '_' | '.' | '~' => c.to_string(),
            ' '  => "+".to_string(),
            _    => format!("%{:02X}", c as u32),
        })
        .collect()
}
