// templates/mod.rs
//
// All HTML generated by Rust functions returning String.
// No template engine — zero overhead, zero mismatches.
//
// Security: every user-supplied string passes through escape_html() before
// insertion.  Template literals are trusted Rust strings only.
//
// Layout
// ──────
//   mod.rs    — shared helpers (base_layout, fmt_ts, …), statics, re-exports
//   board.rs  — index_page, board_page, catalog_page, archive_page, search_page
//   thread.rs — thread_page, render_post, render_poll
//   admin.rs  — admin_panel_page, admin_login_page, mod_log_page, …
//   forms.rs  — new_thread_form, reply_form

use crate::config::CONFIG;
use crate::models::*;
use crate::utils::sanitize::escape_html;
use chrono::{TimeZone, Utc};
use once_cell::sync::Lazy;
use std::sync::RwLock;

pub mod admin;
pub mod board;
pub mod forms;
pub mod thread;

// Re-export every public symbol so all existing call-sites (templates::foo)
// continue to compile without any changes.
pub use admin::*;
pub use board::*;
pub use thread::*;

// ─── Live site name (DB-overridable, falls back to CONFIG.forum_name) ─────────

static LIVE_SITE_NAME: Lazy<RwLock<String>> = Lazy::new(|| RwLock::new(CONFIG.forum_name.clone()));
static LIVE_SITE_SUBTITLE: Lazy<RwLock<String>> =
    Lazy::new(|| RwLock::new("select board to proceed".to_string()));

/// In-memory cache for the admin-configured default theme (empty = terminal).
/// Updated immediately when admin saves site settings so pages reflect the
/// change without requiring a server restart or extra DB round-trip per request.
static LIVE_DEFAULT_THEME: Lazy<RwLock<String>> = Lazy::new(|| RwLock::new(String::new()));

/// Call this at startup (after first DB read) and after admin saves a new name.
pub fn set_live_site_name(name: &str) {
    if let Ok(mut guard) = LIVE_SITE_NAME.write() {
        *guard = if name.trim().is_empty() {
            CONFIG.forum_name.clone()
        } else {
            name.to_string()
        };
    }
}

pub fn set_live_site_subtitle(subtitle: &str) {
    if let Ok(mut guard) = LIVE_SITE_SUBTITLE.write() {
        *guard = if subtitle.trim().is_empty() {
            "select board to proceed".to_string()
        } else {
            subtitle.to_string()
        };
    }
}

/// Update the in-memory default theme cache.
/// Pass an empty string to reset to "terminal" (the built-in default).
pub fn set_live_default_theme(theme: &str) {
    if let Ok(mut guard) = LIVE_DEFAULT_THEME.write() {
        *guard = theme.to_string();
    }
}

/// Read the current live default theme slug.
pub(super) fn live_default_theme() -> String {
    LIVE_DEFAULT_THEME
        .read()
        .map(|g| g.clone())
        .unwrap_or_default()
}

/// Read the current live site name.
pub(super) fn live_site_name() -> String {
    LIVE_SITE_NAME
        .read()
        .map(|g| g.clone())
        .unwrap_or_else(|_| CONFIG.forum_name.clone())
}

pub(super) fn live_site_subtitle() -> String {
    LIVE_SITE_SUBTITLE
        .read()
        .map(|g| g.clone())
        .unwrap_or_else(|_| "select board to proceed".to_string())
}

// ─── Shared JS injected once per page ────────────────────────────────────────

// FIX[NEW-H1]: All JavaScript has been moved to /static/main.js.
// Kept as an empty constant to avoid touching every call-site.
pub(super) const TOGGLE_SCRIPT: &str = "";

// ─── Auto-compress modal ──────────────────────────────────────────────────────

/// Returns the compress-modal overlay HTML.
/// Dynamic size limits are embedded as data-max-image / data-max-video attributes
/// on the modal element and read by main.js at runtime (FIX[NEW-H1]).
pub(super) fn compress_modal_script(max_image_bytes: usize, max_video_bytes: usize) -> String {
    format!(
        r#"
<!-- Auto-compress modal — shared by new-thread and reply forms on this page -->
<div id="compress-modal" class="compress-modal" style="display:none" role="dialog" aria-modal="true" aria-labelledby="compress-modal-title"
     data-max-image="{max_image}" data-max-video="{max_video}">
  <div class="compress-modal-box">
    <div class="compress-modal-title" id="compress-modal-title">&#9888; File Too Large</div>
    <div class="compress-modal-info" id="compress-info"></div>
    <div class="compress-progress" id="compress-progress" style="display:none">
      <div class="compress-progress-track"><div class="compress-progress-bar" id="compress-progress-bar"></div></div>
      <div class="compress-progress-text" id="compress-progress-text">Preparing…</div>
    </div>
    <div class="compress-modal-actions" id="compress-actions">
      <button class="compress-cancel-btn" data-action="dismiss-compress">Cancel</button>
      <button class="compress-do-btn" id="compress-do-btn" data-action="start-compress">&#9881; Auto-compress</button>
    </div>
    <div class="compress-done-actions" id="compress-done-actions" style="display:none">
      <button class="compress-cancel-btn" data-action="dismiss-compress">Close</button>
    </div>
  </div>
</div>"#,
        max_image = max_image_bytes,
        max_video = max_video_bytes,
    )
}

// ─── Report modal ─────────────────────────────────────────────────────────────

/// Returns the report overlay HTML. Injected once per thread page.
// FIX[NEW-H1]: JS functions live in /static/main.js.
pub(super) fn report_modal_script() -> &'static str {
    r#"
<div id="report-modal" class="compress-modal" style="display:none" role="dialog" aria-modal="true">
  <div class="compress-modal-box">
    <div class="compress-modal-title">&#9873; Report Post</div>
    <form method="POST" action="/report" id="report-form">
      <input type="hidden" name="_csrf"     id="report-csrf">
      <input type="hidden" name="post_id"   id="report-post-id">
      <input type="hidden" name="thread_id" id="report-thread-id">
      <input type="hidden" name="board"     id="report-board">
      <div class="compress-modal-info" id="report-info" style="margin-bottom:0.6rem"></div>
      <input type="text" name="reason" id="report-reason"
             placeholder="reason (optional)" maxlength="256"
             style="width:100%;background:var(--bg-input);border:1px solid var(--border);
                    color:var(--text);padding:5px 8px;font-family:var(--font);font-size:0.82rem;
                    box-sizing:border-box;margin-bottom:0.75rem">
      <div class="compress-modal-actions">
        <button type="button" class="compress-cancel-btn" data-action="close-report">Cancel</button>
        <button type="submit" class="compress-do-btn">&#9873; Submit Report</button>
      </div>
    </form>
  </div>
</div>"#
}

// ─── Thread auto-update script ────────────────────────────────────────────────

// FIX[NEW-H1]: All auto-update logic lives in /static/main.js.
pub(super) fn thread_autoupdate_script() -> &'static str {
    ""
}

// ─── Timestamp helpers ────────────────────────────────────────────────────────

pub(super) fn fmt_ts(ts: i64) -> String {
    match Utc.timestamp_opt(ts, 0) {
        chrono::LocalResult::Single(dt) => dt.format("%Y-%m-%d %H:%M:%S UTC").to_string(),
        _ => "unknown".to_string(),
    }
}

pub(super) fn fmt_ts_short(ts: i64) -> String {
    match Utc.timestamp_opt(ts, 0) {
        chrono::LocalResult::Single(dt) => dt.format("%m/%d/%y(%a)%H:%M:%S").to_string(),
        _ => "?".to_string(),
    }
}

// ─── Embed thumbnail helper ───────────────────────────────────────────────────

/// Scan raw post body text for a video embed URL and return its thumbnail URL.
/// Used by catalog and board-index summaries when the OP has no uploaded file.
pub(super) fn embed_thumb_from_body(body: &str) -> Option<String> {
    for token in body.split_whitespace() {
        let clean = token.trim_end_matches(['.', ',', ')', ';', '\'']);
        if let Some((embed_type, id)) = crate::utils::sanitize::extract_video_embed(clean) {
            if embed_type == "youtube" {
                return Some(format!("https://img.youtube.com/vi/{}/mqdefault.jpg", id));
            }
        }
    }
    None
}

// ─── Pagination helper ────────────────────────────────────────────────────────

pub(super) fn render_pagination(p: &Pagination, base_url: &str) -> String {
    if p.total_pages() <= 1 {
        return String::new();
    }
    let sep = if base_url.contains('?') { "&" } else { "?" };
    let mut html = String::from(r#"<div class="pagination">"#);

    if p.has_prev() {
        html.push_str(&format!(
            r#"<a href="{}{sep}page={}">[prev]</a> "#,
            base_url,
            p.page - 1,
            sep = sep
        ));
    }
    html.push_str(&format!("page {} / {}", p.page, p.total_pages()));
    if p.has_next() {
        html.push_str(&format!(
            r#" <a href="{}{sep}page={}">[next]</a>"#,
            base_url,
            p.page + 1,
            sep = sep
        ));
    }

    html.push_str("</div>");
    html
}

// FIX[LOW-9]: Encode each UTF-8 *byte*, not each Unicode codepoint.
// RFC 3986 percent-encoding operates on bytes.
pub(super) fn urlencoding_simple(s: &str) -> String {
    let mut out = String::with_capacity(s.len() * 3);
    for &byte in s.as_bytes() {
        match byte {
            b'A'..=b'Z' | b'a'..=b'z' | b'0'..=b'9' | b'-' | b'_' | b'.' | b'~' => {
                out.push(byte as char)
            }
            b' ' => out.push('+'),
            b => out.push_str(&format!("%{:02X}", b)),
        }
    }
    out
}

// ─── Base layout ─────────────────────────────────────────────────────────────

pub(super) fn base_layout(
    title: &str,
    board_short: Option<&str>,
    body: &str,
    csrf_token: &str,
    boards: &[Board],
    collapse_greentext: bool,
    _allow_archive: bool,
) -> String {
    let inner_links: String = boards
        .iter()
        .map(|b| {
            format!(
                r#"<a href="/{s}/catalog">{s}</a>"#,
                s = escape_html(&b.short_name)
            )
        })
        .collect::<Vec<_>>()
        .join(" / ");
    let board_links = if inner_links.is_empty() {
        String::new()
    } else {
        format!("[ {} ]", inner_links)
    };

    let search_bar = if let Some(b) = board_short {
        format!(
            r#"<form class="search-form" method="GET" action="/{b}/search">
<input type="text" name="q" placeholder="search /{b}/…" maxlength="64">
<button type="submit">go</button>
</form>"#,
            b = escape_html(b)
        )
    } else {
        String::new()
    };

    let default_theme = live_default_theme();
    // Only inject the attribute when a non-default theme is configured — no
    // attribute means "terminal" (the built-in default), matching the
    // client-side behaviour in theme-init.js.
    let default_theme_attr = if !default_theme.is_empty() && default_theme != "terminal" {
        format!(r#" data-default-theme="{}""#, escape_html(&default_theme))
    } else {
        String::new()
    };

    format!(
        r#"<!DOCTYPE html>
<html lang="en"{default_theme_attr}>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="referrer" content="no-referrer">
<title>{title}</title>
<link rel="stylesheet" href="/static/style.css">
<script src="/static/theme-init.js"></script>
</head>
<body{collapse_attr}>
<header class="site-header">
  <span class="site-name">{forum_name}</span>
  <a class="home-btn" href="/">&#8962; Home</a>
  <nav class="board-list">
    {board_links}
  </nav>
  <div class="header-search">{search_bar}</div>
  <a class="admin-header-link" href="/admin">[Admin]</a>
</header>
<main>
{body}
</main>
<footer class="site-footer">
  <p>{forum_name} &mdash; <a href="/">home</a></p>
</footer>

<!-- Theme Picker — FIX[NEW-H1]: onclick= replaced with data-action= attributes -->
<button id="theme-picker-btn" data-action="toggle-theme-picker" title="Select Theme">&#127912; Theme</button>
<div id="theme-picker-panel">
  <div class="tp-title">// SELECT THEME</div>
  <button class="tp-option" data-action="set-theme" data-theme="terminal">
    <span class="tp-swatch" style="background:#00ff41;"></span>Terminal
  </button>
  <button class="tp-option" data-action="set-theme" data-theme="aero">
    <span class="tp-swatch" style="background:#6aaed6;"></span>Frutiger Aero
  </button>
  <button class="tp-option" data-action="set-theme" data-theme="dorfic">
    <span class="tp-swatch" style="background:#ffcc66;"></span>DORFic
  </button>
  <button class="tp-option" data-action="set-theme" data-theme="fluorogrid">
    <span class="tp-swatch" style="background:#8833aa;"></span>FluoroGrid
  </button>
  <button class="tp-option" data-action="set-theme" data-theme="neoncubicle">
    <span class="tp-swatch" style="background:#b03888;"></span>NeonCubicle
  </button>
</div>

<input type="hidden" id="csrf_global" value="{csrf_token}">
<script src="/static/main.js" defer></script>
</body>
</html>"#,
        title = escape_html(title),
        board_links = board_links,
        search_bar = search_bar,
        forum_name = escape_html(&live_site_name()),
        body = body,
        csrf_token = escape_html(csrf_token),
        default_theme_attr = default_theme_attr,
        collapse_attr = if collapse_greentext {
            " data-collapse-greentext=\"1\""
        } else {
            ""
        },
    )
}

// ─── Standalone error/ban pages (no board context) ────────────────────────────

pub fn ban_page(reason: &str) -> String {
    let default_theme = live_default_theme();
    let default_theme_attr = if !default_theme.is_empty() && default_theme != "terminal" {
        format!(r#" data-default-theme="{}""#, escape_html(&default_theme))
    } else {
        String::new()
    };
    format!(
        r#"<!DOCTYPE html>
<html lang="en"{default_theme_attr}>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>You Are Banned</title>
<link rel="stylesheet" href="/static/style.css">
<script src="/static/theme-init.js"></script>
</head>
<body>
<div class="page-box error-page">
<h1>you are banned</h1>
<p style="color:var(--text-dim)">reason: <strong>{reason}</strong></p>
<p style="margin-top:1.5rem;font-size:0.9rem">if you believe this ban was made in error, you may submit an appeal below.<br>
appeals are reviewed by site staff. one appeal per 24 hours.</p>
<form method="POST" action="/appeal" class="appeal-form">
<input type="hidden" name="_csrf" id="appeal-csrf-field" value="">
<textarea name="reason" rows="4" maxlength="512"
  placeholder="Briefly explain why you believe this ban should be lifted…"
  style="width:100%;box-sizing:border-box;margin:0.75rem 0;background:var(--bg-post);color:var(--text);border:1px solid var(--border);padding:0.5rem;resize:vertical"></textarea>
<button type="submit" style="margin-top:0.25rem">submit appeal</button>
</form>
<p style="margin-top:1.5rem"><a href="/">return home</a></p>
</div>
</body>
</html>"#,
        default_theme_attr = default_theme_attr,
        reason = escape_html(reason),
    )
}

pub fn error_page(code: u16, message: &str) -> String {
    let default_theme = live_default_theme();
    let default_theme_attr = if !default_theme.is_empty() && default_theme != "terminal" {
        format!(r#" data-default-theme="{}""#, escape_html(&default_theme))
    } else {
        String::new()
    };
    format!(
        r#"<!DOCTYPE html>
<html lang="en"{default_theme_attr}>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Error {code}</title>
<link rel="stylesheet" href="/static/style.css">
<script src="/static/theme-init.js"></script>
</head>
<body>
<div class="page-box error-page">
<h1>error {code}</h1>
<p>{message}</p>
<p><a href="/">return home</a></p>
</div>
</body>
</html>"#,
        default_theme_attr = default_theme_attr,
        code = code,
        message = escape_html(message),
    )
}
