// templates/mod.rs
//
// All HTML generated by Rust functions returning String.
// No template engine — zero overhead, zero mismatches.
//
// Security: every user-supplied string passes through escape_html() before
// insertion.  Template literals are trusted Rust strings only.

use crate::config::CONFIG;
use crate::models::*;
use crate::utils::{files::format_file_size, sanitize::escape_html};

// ─── Shared JS injected once per page ────────────────────────────────────────

const TOGGLE_SCRIPT: &str = r#"<script>
function togglePostForm() {
  var wrap = document.getElementById('post-form-wrap');
  var btn = document.querySelector('.post-toggle-btn');
  if (!wrap) return;
  var opening = wrap.style.display === 'none';
  wrap.style.display = opening ? 'block' : 'none';
  if (btn) btn.classList.toggle('active', opening);
  if (opening) {
    var first = wrap.querySelector('input[type="text"], textarea');
    if (first) first.focus();
  }
}
function appendReply(id) {
  var wrap = document.getElementById('post-form-wrap');
  if (wrap && wrap.style.display === 'none') togglePostForm();
  var ta = document.getElementById('reply-body');
  if (ta) { ta.value += '>>' + id + '\n'; ta.focus(); }
  return false;
}
function expandMedia(preview) {
  var container = preview.closest('.file-container');
  var expanded = container.querySelector('.media-expanded');
  var closeBtn = container.querySelector('.media-close-btn');
  if (expanded.tagName === 'IMG' && expanded.dataset.src) {
    expanded.src = expanded.dataset.src;
    delete expanded.dataset.src;
  }
  preview.style.display = 'none';
  expanded.style.display = 'block';
  closeBtn.style.display = 'inline-flex';
  if (expanded.tagName === 'VIDEO') {
    expanded.play().catch(function(){});
  }
}
function collapseMedia(btn) {
  var container = btn.closest('.file-container');
  var expanded = container.querySelector('.media-expanded');
  var preview = container.querySelector('.media-preview');
  if (expanded.tagName === 'VIDEO') {
    expanded.pause();
    expanded.currentTime = 0;
  }
  expanded.style.display = 'none';
  expanded.style.maxWidth = '';
  expanded.style.maxHeight = '';
  preview.style.display = 'block';
  btn.style.display = 'none';
}
</script>"#;
use chrono::{TimeZone, Utc};

// ─── Timestamp helpers ────────────────────────────────────────────────────────

fn fmt_ts(ts: i64) -> String {
    match Utc.timestamp_opt(ts, 0) {
        chrono::LocalResult::Single(dt) => dt.format("%Y-%m-%d %H:%M:%S UTC").to_string(),
        _ => "unknown".to_string(),
    }
}

fn fmt_ts_short(ts: i64) -> String {
    match Utc.timestamp_opt(ts, 0) {
        chrono::LocalResult::Single(dt) => dt.format("%m/%d/%y(%a)%H:%M:%S").to_string(),
        _ => "?".to_string(),
    }
}

// ─── Base layout ─────────────────────────────────────────────────────────────

fn base_layout(
    title: &str,
    board_short: Option<&str>,
    body: &str,
    csrf_token: &str,
    boards: &[Board],
    collapse_greentext: bool,
) -> String {
    let board_links: String = boards
        .iter()
        .map(|b| {
            format!(
                r#"[<a href="/{s}/catalog">{s}</a>]"#,
                s = escape_html(&b.short_name)
            )
        })
        .collect::<Vec<_>>()
        .join(" ");

    let search_bar = if let Some(b) = board_short {
        format!(
            r#"<form class="search-form" method="GET" action="/{b}/search">
<input type="text" name="q" placeholder="search /{b}/…" maxlength="64">
<button type="submit">go</button>
</form>"#,
            b = escape_html(b)
        )
    } else {
        String::new()
    };

    // Sticky catalog bar shown when browsing a specific board
    let catalog_bar = if let Some(b) = board_short {
        format!(
            r#"<div class="catalog-bar">
  <a class="catalog-bar-link" href="/{b}/catalog">[ /{b}/ catalog ]</a>
  <span class="catalog-bar-sep">|</span>
  <a class="catalog-bar-link" href="/{b}/">[ /{b}/ index ]</a>
</div>"#,
            b = escape_html(b)
        )
    } else {
        String::new()
    };

    format!(
        r#"<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="referrer" content="no-referrer">
<title>{title}</title>
<link rel="stylesheet" href="/static/style.css">
<script>try{{var _t=localStorage.getItem('rustchan_theme');if(_t&&_t!=='terminal')document.documentElement.setAttribute('data-theme',_t);}}catch(e){{}}</script>
</head>
<body{collapse_attr}>
<header class="site-header">
  <a class="home-btn" href="/">&#8962; Home</a>
  <nav class="board-list">
    {board_links}
    [<a href="/admin">Admin</a>]
  </nav>
  <div class="header-search">{search_bar}</div>
</header>
{catalog_bar}
<main>
{body}
</main>
<footer class="site-footer">
  <p>{forum_name} &mdash; <a href="/">home</a></p>
</footer>

<!-- Theme Picker -->
<button id="theme-picker-btn" onclick="toggleThemePicker()" title="Select Theme">&#9681; Theme</button>
<div id="theme-picker-panel">
  <div class="tp-title">// SELECT THEME</div>
  <button class="tp-option" onclick="setTheme('terminal')">
    <span class="tp-swatch" style="background:#050505;border-color:#00c840;"></span>Terminal
  </button>
  <button class="tp-option" onclick="setTheme('aero')">
    <span class="tp-swatch" style="background:linear-gradient(135deg,#b8e0f8,#dff4ff);border-color:#38b6ff;"></span>Frutiger Aero
  </button>
  <button class="tp-option" onclick="setTheme('dorfic')">
    <span class="tp-swatch" style="background:#FFD700;border-color:#FF4500;"></span>DORFic
  </button>
  <button class="tp-option" onclick="setTheme('fluorogrid')">
    <span class="tp-swatch" style="background:#D0FFE0;border-color:#00FFFF;"></span>FluoroGrid
  </button>
  <button class="tp-option" onclick="setTheme('neoncubicle')">
    <span class="tp-swatch" style="background:#F0F4F8;border-color:#0FF0FF;"></span>NeonCubicle
  </button>
</div>

<script>
(function() {{
  var THEMES = ['terminal','aero','dorfic','fluorogrid','neoncubicle'];

  function applyTheme(t) {{
    if (t === 'terminal') {{
      document.documentElement.removeAttribute('data-theme');
    }} else {{
      document.documentElement.setAttribute('data-theme', t);
    }}
    document.querySelectorAll('.tp-option').forEach(function(el, i) {{
      el.classList.toggle('active', THEMES[i] === t);
    }});
  }}

  function setTheme(t) {{
    try {{ localStorage.setItem('rustchan_theme', t); }} catch(e) {{}}
    applyTheme(t);
    closeThemePicker();
  }}

  function toggleThemePicker() {{
    var p = document.getElementById('theme-picker-panel');
    p.classList.toggle('open');
  }}

  function closeThemePicker() {{
    document.getElementById('theme-picker-panel').classList.remove('open');
  }}

  // Close panel on outside click
  document.addEventListener('click', function(e) {{
    var btn = document.getElementById('theme-picker-btn');
    var panel = document.getElementById('theme-picker-panel');
    if (!btn.contains(e.target) && !panel.contains(e.target)) {{
      closeThemePicker();
    }}
  }});

  // Expose for inline onclick
  window.setTheme = setTheme;
  window.toggleThemePicker = toggleThemePicker;

  // Apply saved theme on load (avoids flash)
  try {{
    var saved = localStorage.getItem('rustchan_theme');
    if (saved && THEMES.indexOf(saved) !== -1) {{ applyTheme(saved); }}
  }} catch(e) {{}}
}})();
</script>

<input type="hidden" id="csrf_global" value="{csrf_token}">
<script>
// Collapse greentext walls when the admin has enabled the feature.
// The page injects data-collapse-greentext on <body> when the setting is on.
(function() {{
  if (document.body.getAttribute('data-collapse-greentext') === '1') {{
    document.querySelectorAll('details.greentext-block').forEach(function(el) {{
      el.removeAttribute('open');
    }});
  }}
}})();
</script>
</body>
</html>"#,
        title = escape_html(title),
        board_links = board_links,
        search_bar = search_bar,
        catalog_bar = catalog_bar,
        forum_name = escape_html(&CONFIG.forum_name),
        body = body,
        csrf_token = escape_html(csrf_token),
        collapse_attr = if collapse_greentext {
            " data-collapse-greentext=\"1\""
        } else {
            ""
        },
    )
}

// ─── Index (board list) ───────────────────────────────────────────────────────

pub fn index_page(
    board_stats: &[crate::models::BoardStats],
    site_stats: &crate::models::SiteStats,
    csrf_token: &str,
) -> String {
    // Build a plain boards list for the nav bar
    let all_boards: Vec<Board> = board_stats.iter().map(|s| s.board.clone()).collect();

    let sfw: Vec<&crate::models::BoardStats> =
        board_stats.iter().filter(|s| !s.board.nsfw).collect();
    let nsfw: Vec<&crate::models::BoardStats> =
        board_stats.iter().filter(|s| s.board.nsfw).collect();

    fn board_cards(list: &[&crate::models::BoardStats]) -> String {
        list.iter()
            .map(|s| {
                let b = &s.board;
                let nsfw_badge = if b.nsfw {
                    r#"<span class="nsfw-badge">NSFW</span>"#
                } else {
                    ""
                };
                let thread_word = if s.thread_count == 1 {
                    "thread"
                } else {
                    "threads"
                };
                format!(
                    r#"<a class="board-card" href="/{sh}/catalog">
  <div class="board-card-short">/{sh}/</div>
  <div class="board-card-name">{n}{nsfw}</div>
  <div class="board-card-desc">{d}</div>
  <div class="board-card-stats">{tc} {tw}</div>
</a>"#,
                    sh = escape_html(&b.short_name),
                    n = escape_html(&b.name),
                    nsfw = nsfw_badge,
                    d = escape_html(&b.description),
                    tc = s.thread_count,
                    tw = thread_word,
                )
            })
            .collect()
    }

    let sfw_sec = if !sfw.is_empty() {
        format!("<div class=\"index-section\"><h2 class=\"index-section-title\">// Boards</h2><div class=\"board-cards\">{}</div></div>", board_cards(&sfw))
    } else {
        String::new()
    };

    let nsfw_sec = if !nsfw.is_empty() {
        format!("<div class=\"index-section\"><h2 class=\"index-section-title\">// Adult Boards <span class=\"nsfw-badge\">NSFW</span></h2><div class=\"board-cards\">{}</div></div>", board_cards(&nsfw))
    } else {
        String::new()
    };

    let empty = if board_stats.is_empty() {
        "<p class=\"index-empty\">no boards yet — admin must create boards first.</p>"
    } else {
        ""
    };

    let active_gb = site_stats.active_bytes as f64 / (1024.0 * 1024.0 * 1024.0);
    let stats_sec = format!(
        r#"<div class="index-section index-stats-section">
<h2 class="index-section-title">// Stats</h2>
<div class="index-stats-grid">
  <div class="index-stat"><span class="index-stat-value">{tp}</span><span class="index-stat-label">total posts</span></div>
  <div class="index-stat"><span class="index-stat-value">{ti}</span><span class="index-stat-label">images uploaded</span></div>
  <div class="index-stat"><span class="index-stat-value">{tv}</span><span class="index-stat-label">videos uploaded</span></div>
  <div class="index-stat"><span class="index-stat-value">{ta}</span><span class="index-stat-label">audio files uploaded</span></div>
  <div class="index-stat"><span class="index-stat-value">{gb:.2} GB</span><span class="index-stat-label">active content</span></div>
</div>
</div>"#,
        tp = site_stats.total_posts,
        ti = site_stats.total_images,
        tv = site_stats.total_videos,
        ta = site_stats.total_audio,
        gb = active_gb,
    );

    let body = format!(
        r#"<div class="index-hero">
<h1 class="index-title">[ {name} ]</h1>
<p class="index-subtitle">select board to proceed</p>
</div>
{sfw}{nsfw}{empty}{stats}"#,
        name = escape_html(&CONFIG.forum_name),
        sfw = sfw_sec,
        nsfw = nsfw_sec,
        empty = empty,
        stats = stats_sec,
    );

    base_layout(
        &CONFIG.forum_name,
        None,
        &body,
        csrf_token,
        &all_boards,
        false,
    )
}

// ─── Board index ──────────────────────────────────────────────────────────────

#[allow(clippy::too_many_arguments)]
pub fn board_page(
    board: &Board,
    summaries: &[ThreadSummary],
    pagination: &Pagination,
    csrf_token: &str,
    boards: &[Board],
    is_admin: bool,
    error: Option<&str>,
    collapse_greentext: bool,
) -> String {
    let mut body = String::new();

    // Inline error banner (e.g. validation failures on post submission)
    if let Some(msg) = error {
        body.push_str(&format!(
            r#"<div class="post-error-banner">&#9888; {}</div>"#,
            escape_html(msg)
        ));
    }

    // Visible admin toolbar — appears whenever an admin is logged in
    if is_admin {
        body.push_str(&format!(
            r#"<div class="admin-toolbar">
<span class="admin-toolbar-label">&#9632; ADMIN</span>
<a href="/admin/panel">panel</a>
<form method="POST" action="/admin/logout" style="display:inline">
<input type="hidden" name="_csrf" value="{csrf}">
<button type="submit" class="admin-toolbar-btn">logout</button>
</form>
</div>"#,
            csrf = escape_html(csrf_token),
        ));
    }

    body.push_str(&format!(
        r#"<div class="board-header"><h1>/{short}/  — {name}</h1><p class="board-desc">{desc}</p></div>"#,
        short = escape_html(&board.short_name),
        name = escape_html(&board.name),
        desc = escape_html(&board.description),
    ));

    body.push_str(&format!(
        r#"<div class="post-toggle-bar centered">
  <button class="post-toggle-btn" onclick="togglePostForm()">[ Start a New Thread ]</button>
</div>
<div class="post-form-wrap" id="post-form-wrap" style="display:none">
  {}
</div>"#,
        new_thread_form(&board.short_name, csrf_token),
    ));

    for summary in summaries {
        body.push_str(&render_thread_summary(
            summary,
            &board.short_name,
            csrf_token,
            is_admin,
        ));
    }

    body.push_str(&render_pagination(
        pagination,
        &format!("/{}/", board.short_name),
    ));

    body.push_str(TOGGLE_SCRIPT);

    base_layout(
        &format!("/{}/", board.short_name),
        Some(&board.short_name),
        &body,
        csrf_token,
        boards,
        collapse_greentext,
    )
}

fn new_thread_form(board_short: &str, csrf_token: &str) -> String {
    let image_mb = crate::config::CONFIG.max_image_size / 1024 / 1024;
    let video_mb = crate::config::CONFIG.max_video_size / 1024 / 1024;
    let audio_mb = crate::config::CONFIG.max_audio_size / 1024 / 1024;
    format!(
        r#"<div class="post-form-container">
<div class="post-form-title">[ new thread ]</div>
<form class="post-form" method="POST" action="/{board}/" enctype="multipart/form-data">
  <input type="hidden" name="_csrf" value="{csrf}">
  <table>
    <tr><td>name</td>
        <td><input type="text" name="name" placeholder="Anonymous" maxlength="64"></td></tr>
    <tr><td>subject</td>
        <td><input type="text" name="subject" maxlength="128">
            <button type="submit">post thread</button></td></tr>
    <tr><td>body</td>
        <td><textarea name="body" rows="5" maxlength="4096"></textarea>
            <div class="markup-hint">
              <span title="Greentext">&#62;green</span>
              <span title="Bold">**bold**</span>
              <span title="Italic">__italic__</span>
              <span title="Spoiler">[spoiler]text[/spoiler]</span>
              <span title="Reply">&gt;&gt;123</span>
              <span title="Cross-thread">&gt;&gt;&gt;/b/123</span>
              <span title="Emoji">:fire:</span>
            </div>
        </td></tr>
    <tr><td>file</td>
        <td><input type="file" name="file" accept="image/jpeg,image/png,image/gif,image/webp,video/mp4,video/webm,audio/mpeg,audio/ogg,audio/flac,audio/wav,audio/mp4,audio/aac,audio/webm,.mp3,.ogg,.flac,.wav,.m4a,.aac">
            <span style="font-size:0.72rem;color:var(--text-dim)">jpg/png/gif/webp · max {image_mb} MiB &nbsp;|&nbsp; mp4/webm · max {video_mb} MiB &nbsp;|&nbsp; mp3/ogg/flac/wav/m4a · max {audio_mb} MiB</span></td></tr>
    <tr><td>del token</td>
        <td><input type="text" name="deletion_token" placeholder="password to delete" maxlength="64"></td></tr>
    <tr><td colspan="2">
      <details class="poll-creator">
        <summary>[ 📊 Add a Poll to this thread ]</summary>
        <div class="poll-creator-inner">
          <div class="poll-creator-row">
            <label>Question<input type="text" name="poll_question" placeholder="What do you think?" maxlength="256"></label>
          </div>
          <div id="poll-options-list">
            <div class="poll-option-row"><input type="text" name="poll_option" placeholder="Option 1" maxlength="128"><button type="button" class="poll-remove-btn" onclick="removePollOption(this)" style="display:none">✕</button></div>
            <div class="poll-option-row"><input type="text" name="poll_option" placeholder="Option 2" maxlength="128"><button type="button" class="poll-remove-btn" onclick="removePollOption(this)" style="display:none">✕</button></div>
          </div>
          <button type="button" class="poll-add-btn" onclick="addPollOption()">+ Add Option</button>
          <div class="poll-creator-row poll-duration-row">
            <label>Duration
              <input type="number" name="poll_duration_value" value="24" min="1" max="720" class="poll-duration-input">
              <select name="poll_duration_unit" class="poll-duration-unit">
                <option value="hours">Hours</option>
                <option value="minutes">Minutes</option>
              </select>
            </label>
          </div>
        </div>
      </details>
    </td></tr>
  </table>
</form>
</div>
<script>
function addPollOption() {{
  var list = document.getElementById('poll-options-list');
  var count = list.querySelectorAll('.poll-option-row').length + 1;
  if (count > 10) return;
  var row = document.createElement('div');
  row.className = 'poll-option-row';
  row.innerHTML = '<input type="text" name="poll_option" placeholder="Option ' + count + '" maxlength="128">'
    + '<button type="button" class="poll-remove-btn" onclick="removePollOption(this)">✕</button>';
  list.appendChild(row);
  updateRemoveButtons();
}}
function removePollOption(btn) {{
  btn.closest('.poll-option-row').remove();
  updateRemoveButtons();
}}
function updateRemoveButtons() {{
  var rows = document.querySelectorAll('#poll-options-list .poll-option-row');
  rows.forEach(function(r, i) {{
    var btn = r.querySelector('.poll-remove-btn');
    if (btn) btn.style.display = rows.length > 2 ? 'inline' : 'none';
  }});
}}
</script>"#,
        board = escape_html(board_short),
        csrf = escape_html(csrf_token),
        image_mb = image_mb,
        video_mb = video_mb,
        audio_mb = audio_mb,
    )
}

fn render_thread_summary(
    summary: &ThreadSummary,
    board_short: &str,
    csrf_token: &str,
    is_admin: bool,
) -> String {
    let t = &summary.thread;
    let mut html = String::new();

    let sticky_label = if t.sticky {
        r#"<span class="tag sticky">STICKY</span> "#
    } else {
        ""
    };
    let locked_label = if t.locked {
        r#"<span class="tag locked">LOCKED</span> "#
    } else {
        ""
    };

    html.push_str(&format!(
        r#"<div class="thread" id="t{tid}">
<div class="op post" id="p{op_id}">"#,
        tid = t.id,
        op_id = t.op_id.unwrap_or(0),
    ));

    if let (Some(_file), Some(thumb)) = (&t.op_file, &t.op_thumb) {
        html.push_str(&format!(
            r#"<div class="file-container"><a href="/{board}/thread/{tid}"><img class="thumb" src="/boards/{th}" loading="lazy" alt="image"></a></div>"#,
            board = escape_html(board_short),
            tid = t.id,
            th = escape_html(thumb),
        ));
    }

    html.push_str(&format!(
        r#"<div class="post-meta">
{sticky}{locked}
<strong class="name">{name}</strong>
<span class="post-time">{time}</span>
<a class="post-num" href="/{board}/thread/{tid}">No.{op_id}</a>
<a class="thread-id-link" href="/{board}/thread/{tid}" title="Thread #{tid}">[ #{tid} ]</a>
</div>"#,
        sticky = sticky_label,
        locked = locked_label,
        name = escape_html(t.op_name.as_deref().unwrap_or("Anonymous")),
        time = fmt_ts_short(t.created_at),
        board = escape_html(board_short),
        tid = t.id,
        op_id = t.op_id.unwrap_or(0),
    ));

    if let Some(subject) = &t.subject {
        html.push_str(&format!(
            r#"<div class="subject"><a href="/{b}/thread/{tid}"><strong>{s}</strong></a></div>"#,
            b = escape_html(board_short),
            tid = t.id,
            s = escape_html(subject),
        ));
    }

    if let Some(body) = &t.op_body {
        let truncated = if body.len() > 300 {
            format!(
                r#"{} <a href="/{b}/thread/{tid}">…[Read more]</a>"#,
                escape_html(&body[..300]),
                b = escape_html(board_short),
                tid = t.id,
            )
        } else {
            escape_html(body)
        };
        html.push_str(&format!(r#"<div class="post-body">{}</div>"#, truncated));
    }

    html.push_str(&format!(
        r#"<div class="thread-footer">
<a href="/{board}/thread/{tid}">[reply] ({n} {word})</a>"#,
        board = escape_html(board_short),
        tid = t.id,
        n = t.reply_count,
        word = if t.reply_count == 1 {
            "reply"
        } else {
            "replies"
        },
    ));

    // Admin: sticky/lock/delete controls on board index
    if is_admin {
        let sticky_act = if t.sticky { "unsticky" } else { "sticky" };
        let sticky_lbl = if t.sticky {
            "&#128204; unsticky"
        } else {
            "&#128204; sticky"
        };
        let lock_act = if t.locked { "unlock" } else { "lock" };
        let lock_lbl = if t.locked {
            "&#128275; unlock"
        } else {
            "&#128274; lock"
        };
        html.push_str(&format!(
            r#" <form method="POST" action="/admin/thread/action" style="display:inline">
<input type="hidden" name="_csrf"      value="{csrf}">
<input type="hidden" name="thread_id"  value="{tid}">
<input type="hidden" name="board"      value="{board}">
<input type="hidden" name="action"     value="{sticky_act}">
<button type="submit" class="admin-del-btn">{sticky_lbl}</button>
</form>
<form method="POST" action="/admin/thread/action" style="display:inline">
<input type="hidden" name="_csrf"      value="{csrf}">
<input type="hidden" name="thread_id"  value="{tid}">
<input type="hidden" name="board"      value="{board}">
<input type="hidden" name="action"     value="{lock_act}">
<button type="submit" class="admin-del-btn">{lock_lbl}</button>
</form>
<form method="POST" action="/admin/thread/delete" style="display:inline">
<input type="hidden" name="_csrf"      value="{csrf}">
<input type="hidden" name="thread_id"  value="{tid}">
<input type="hidden" name="board"      value="{board}">
<button type="submit" class="admin-del-btn"
        onclick="return confirm('Delete thread No.{tid} and all its posts?')">&#x2715; del</button>
</form>"#,
            csrf = escape_html(csrf_token),
            tid = t.id,
            board = escape_html(board_short),
            sticky_act = sticky_act,
            sticky_lbl = sticky_lbl,
            lock_act = lock_act,
            lock_lbl = lock_lbl,
        ));
    }

    html.push_str("</div>\n</div>");

    if summary.omitted > 0 {
        html.push_str(&format!(
            r#"<div class="omitted">{} posts omitted. <a href="/{b}/thread/{tid}">view thread</a></div>"#,
            summary.omitted,
            b = escape_html(board_short),
            tid = t.id,
        ));
    }

    for post in &summary.preview_posts {
        html.push_str(&render_post(
            post,
            board_short,
            csrf_token,
            false,
            is_admin,
            true,
        ));
    }

    html.push_str("<hr class=\"thread-sep\">");
    html
}

// ─── Thread page ──────────────────────────────────────────────────────────────

#[allow(clippy::too_many_arguments)]
pub fn thread_page(
    board: &Board,
    thread: &Thread,
    posts: &[Post],
    csrf_token: &str,
    boards: &[Board],
    is_admin: bool,
    poll: Option<&crate::models::PollData>,
    error: Option<&str>,
    collapse_greentext: bool,
) -> String {
    let mut body = String::new();

    // Inline error banner (e.g. validation failures on reply submission)
    if let Some(msg) = error {
        body.push_str(&format!(
            r#"<div class="post-error-banner">&#9888; {}</div>"#,
            escape_html(msg)
        ));
    }

    // Visible admin toolbar
    if is_admin {
        let sticky_action = if thread.sticky {
            ("unsticky", "&#128204; Unsticky")
        } else {
            ("sticky", "&#128204; Sticky")
        };
        let lock_action = if thread.locked {
            ("unlock", "&#128275; Unlock")
        } else {
            ("lock", "&#128274; Lock")
        };
        body.push_str(&format!(
            r#"<div class="admin-toolbar">
<span class="admin-toolbar-label">&#9632; ADMIN</span>
<a href="/admin/panel">panel</a>
<form method="POST" action="/admin/thread/action" style="display:inline">
<input type="hidden" name="_csrf" value="{csrf}">
<input type="hidden" name="thread_id" value="{tid}">
<input type="hidden" name="action" value="{sticky_act}">
<input type="hidden" name="board" value="{board}">
<button type="submit" class="admin-toolbar-btn">{sticky_lbl}</button>
</form>
<form method="POST" action="/admin/thread/action" style="display:inline">
<input type="hidden" name="_csrf" value="{csrf}">
<input type="hidden" name="thread_id" value="{tid}">
<input type="hidden" name="action" value="{lock_act}">
<input type="hidden" name="board" value="{board}">
<button type="submit" class="admin-toolbar-btn">{lock_lbl}</button>
</form>
<form method="POST" action="/admin/thread/delete" style="display:inline">
<input type="hidden" name="_csrf" value="{csrf}">
<input type="hidden" name="thread_id" value="{tid}">
<input type="hidden" name="board" value="{board}">
<button type="submit" class="admin-toolbar-btn admin-toolbar-danger"
        onclick="return confirm('Delete this entire thread and all its posts?')">&#x2715; delete thread</button>
</form>
<form method="POST" action="/admin/logout" style="display:inline">
<input type="hidden" name="_csrf" value="{csrf}">
<button type="submit" class="admin-toolbar-btn">logout</button>
</form>
</div>"#,
            csrf = escape_html(csrf_token),
            tid = thread.id,
            board = escape_html(&board.short_name),
            sticky_act = sticky_action.0,
            sticky_lbl = sticky_action.1,
            lock_act = lock_action.0,
            lock_lbl = lock_action.1,
        ));
    }

    let locked_notice = if thread.locked {
        r#"<div class="notice locked-notice">this thread is locked — no new replies allowed</div>"#
    } else {
        ""
    };

    body.push_str(&format!(
        r#"<div class="board-header">
<a href="/{s}/">[ return ]</a> | <a href="/{s}/catalog">[ catalog ]</a>
<span class="thread-id-badge" id="poll">Thread No.<strong>{tid}</strong></span>
</div>
"#,
        s = escape_html(&board.short_name),
        tid = thread.id,
    ));
    body.push_str(locked_notice);

    // Poll (anchored at #poll)
    if let Some(pd) = poll {
        body.push_str(&render_poll(pd, thread.id, &board.short_name, csrf_token));
    }

    for post in posts {
        body.push_str(&render_post(
            post,
            &board.short_name,
            csrf_token,
            true,
            is_admin,
            true,
        ));
    }

    if !thread.locked {
        body.push_str(&format!(
            r#"<div class="post-toggle-bar reply">
  <button class="post-toggle-btn" onclick="togglePostForm()">[ Reply ]</button>
</div>
<div class="post-form-wrap" id="post-form-wrap" style="display:none">
  {}
</div>"#,
            reply_form(&board.short_name, thread.id, csrf_token),
        ));
    }

    body.push_str(TOGGLE_SCRIPT);

    base_layout(
        &format!(
            "/{}/  {}",
            board.short_name,
            thread.subject.as_deref().unwrap_or("thread")
        ),
        Some(&board.short_name),
        &body,
        csrf_token,
        boards,
        collapse_greentext,
    )
}

// ─── Poll renderer ────────────────────────────────────────────────────────────

fn render_poll(
    pd: &crate::models::PollData,
    thread_id: i64,
    board_short: &str,
    csrf_token: &str,
) -> String {
    let now = chrono::Utc::now().timestamp();
    let time_left = pd.poll.expires_at - now;
    let expires_str = if pd.is_expired {
        "closed".to_string()
    } else if time_left < 3600 {
        format!("closes in {}m", time_left / 60)
    } else if time_left < 86400 {
        format!(
            "closes in {}h {}m",
            time_left / 3600,
            (time_left % 3600) / 60
        )
    } else {
        format!("closes {}", fmt_ts(pd.poll.expires_at))
    };

    let show_results = pd.is_expired || pd.user_voted_option.is_some();

    let mut html = format!(
        r#"<div class="poll-container">
<div class="poll-header">
  <span class="poll-icon">📊</span>
  <span class="poll-question">{q}</span>
  <span class="poll-status {status_class}">[{expires}]</span>
</div>"#,
        q = escape_html(&pd.poll.question),
        status_class = if pd.is_expired {
            "poll-closed"
        } else {
            "poll-open"
        },
        expires = expires_str,
    );

    if show_results {
        // Results view
        let total = pd.total_votes.max(1);
        html.push_str(r#"<div class="poll-results">"#);
        for opt in &pd.options {
            let pct = (opt.vote_count as f64 / total as f64 * 100.0).round() as i64;
            let is_voted = pd.user_voted_option == Some(opt.id);
            html.push_str(&format!(
                r#"<div class="poll-option-result{voted}">
  <div class="poll-option-label">
    {check}<span class="poll-opt-text">{text}</span>
    <span class="poll-opt-count">{votes} ({pct}%)</span>
  </div>
  <div class="poll-bar-track"><div class="poll-bar-fill" style="width:{pct}%"></div></div>
</div>"#,
                voted = if is_voted { " user-voted" } else { "" },
                check = if is_voted { "✓ " } else { "" },
                text = escape_html(&opt.text),
                votes = opt.vote_count,
                pct = pct,
            ));
        }
        html.push_str(&format!(
            r#"<div class="poll-total">{} total vote{}</div></div>"#,
            pd.total_votes,
            if pd.total_votes == 1 { "" } else { "s" },
        ));
    } else {
        // Voting form
        html.push_str(&format!(
            r#"<form class="poll-vote-form" method="POST" action="/vote">
<input type="hidden" name="_csrf"     value="{csrf}">
<input type="hidden" name="thread_id" value="{tid}">
<input type="hidden" name="board"     value="{board}">"#,
            csrf = escape_html(csrf_token),
            tid = thread_id,
            board = escape_html(board_short),
        ));
        for opt in &pd.options {
            html.push_str(&format!(
                r#"<label class="poll-vote-option">
  <input type="radio" name="option_id" value="{id}" required>
  <span class="poll-opt-text">{text}</span>
</label>"#,
                id = opt.id,
                text = escape_html(&opt.text),
            ));
        }
        html.push_str(
            r#"<button type="submit" class="poll-vote-btn">[ Cast Vote ]</button></form>"#,
        );
    }

    html.push_str("</div>");
    html
}

pub fn render_post(
    post: &Post,
    board_short: &str,
    csrf_token: &str,
    show_delete: bool,
    is_admin: bool,
    show_media: bool,
) -> String {
    let tripcode_html = post
        .tripcode
        .as_ref()
        .map(|t| format!(r#"<span class="tripcode">!{}</span>"#, escape_html(t)))
        .unwrap_or_default();

    let op_class = if post.is_op { " op" } else { " reply" };

    let mut html = format!(
        r##"<div class="post{op_class}" id="p{id}">
<div class="post-meta">
<strong class="name">{name}</strong>{tripcode}
<span class="post-time">{time}</span>
<a class="post-num" href="#p{id}" onclick="appendReply({id})">No.{id}</a>
</div>"##,
        op_class = op_class,
        id = post.id,
        name = escape_html(&post.name),
        tripcode = tripcode_html,
        time = fmt_ts_short(post.created_at),
    );

    if let Some(subject) = &post.subject {
        html.push_str(&format!(
            r#"<div class="subject"><strong>{}</strong></div>"#,
            escape_html(subject)
        ));
    }

    // Image / Video / Audio — uses flex layout so text wraps naturally at any size
    if show_media {
        if let (Some(file), Some(thumb)) = (&post.file_path, &post.thumb_path) {
            let size_str = post.file_size.map(format_file_size).unwrap_or_default();
            let name_str = post.file_name.as_deref().unwrap_or("file");
            let mime = post
                .mime_type
                .as_deref()
                .unwrap_or("application/octet-stream");
            // Use explicit media_type when available; fall back to MIME prefix sniff.
            let is_audio = matches!(&post.media_type, Some(crate::models::MediaType::Audio))
                || post
                    .mime_type
                    .as_deref()
                    .map(|m| m.starts_with("audio/"))
                    .unwrap_or(false);
            let is_video = !is_audio
                && (matches!(&post.media_type, Some(crate::models::MediaType::Video))
                    || post
                        .mime_type
                        .as_deref()
                        .map(|m| m.starts_with("video/"))
                        .unwrap_or(false));

            if is_audio {
                // ── Audio player ─────────────────────────────────────────────────
                // Rendered with <audio controls preload="none"> for zero auto-load.
                // The SVG placeholder icon is shown above the player.
                html.push_str(&format!(
                    r#"<div class="file-container audio-container">
<div class="file-info">
  <a href="/boards/{f}">{orig}</a> ({sz})
</div>
<div class="audio-thumb">
  <img class="thumb" src="/boards/{th}" loading="lazy" alt="audio">
</div>
<audio controls preload="none" class="audio-player">
  <source src="/boards/{f}" type="{mime}">
  Your browser does not support the audio element.
</audio>
</div>"#,
                    f = escape_html(file),
                    th = escape_html(thumb),
                    orig = escape_html(name_str),
                    sz = escape_html(&size_str),
                    mime = escape_html(mime),
                ));
            } else if is_video {
                html.push_str(&format!(
                r#"<div class="file-container">
<div class="file-info">
  <a href="/boards/{f}">{orig}</a> ({sz})
  <button class="media-close-btn" onclick="collapseMedia(this)" style="display:none">&#x2715; close</button>
</div>
<div class="media-preview" onclick="expandMedia(this)" title="click to play">
  <img class="thumb" src="/boards/{th}" loading="lazy" alt="video thumbnail">
  <div class="media-expand-overlay">&#9654;</div>
</div>
<video class="media-expanded" src="/boards/{f}" controls preload="none"
       type="{mime}" style="display:none"></video>
</div>"#,
                f = escape_html(file),
                th = escape_html(thumb),
                orig = escape_html(name_str),
                sz = escape_html(&size_str),
                mime = escape_html(mime),
            ));
            } else {
                html.push_str(&format!(
                r#"<div class="file-container">
<div class="file-info">
  <a href="/boards/{f}">{orig}</a> ({sz})
  <button class="media-close-btn" onclick="collapseMedia(this)" style="display:none">&#x2715; close</button>
</div>
<div class="media-preview" onclick="expandMedia(this)" title="click to expand">
  <img class="thumb" src="/boards/{th}" loading="lazy" alt="image">
  <div class="media-expand-overlay">&#x2922;</div>
</div>
<img class="media-expanded" src="" data-src="/boards/{f}" style="display:none"
     alt="image" draggable="false">
</div>"#,
                f = escape_html(file),
                th = escape_html(thumb),
                orig = escape_html(name_str),
                sz = escape_html(&size_str),
            ));
            }
        }
    } // end show_media

    // Post body (pre-rendered, sanitised HTML)
    html.push_str(&format!(
        r#"<div class="post-body">{}</div>"#,
        post.body_html
    ));

    // User delete form (only on thread pages where show_delete=true)
    if show_delete {
        html.push_str(&format!(
            r#"<div class="post-controls">
<form class="delete-form" method="POST" action="/delete">
<input type="hidden" name="_csrf"    value="{csrf}">
<input type="hidden" name="post_id"  value="{pid}">
<input type="hidden" name="board"    value="{board}">
<input type="text"   name="deletion_token" placeholder="del token" maxlength="64" size="12">
<button type="submit" class="del-btn">del</button>
</form>
</div>"#,
            csrf = escape_html(csrf_token),
            pid = post.id,
            board = escape_html(board_short),
        ));
    }

    // Admin delete button — shown whenever admin is logged in, regardless of page
    if is_admin {
        html.push_str(&format!(
            r#"<div class="post-controls admin-post-controls">
<form method="POST" action="/admin/post/delete">
<input type="hidden" name="_csrf"   value="{csrf}">
<input type="hidden" name="post_id" value="{pid}">
<input type="hidden" name="board"   value="{board}">
<button type="submit" class="admin-del-btn"
        onclick="return confirm('Admin delete post No.{pid}?')">&#x2715; admin del</button>
</form>
</div>"#,
            csrf = escape_html(csrf_token),
            pid = post.id,
            board = escape_html(board_short),
        ));
    }

    html.push_str("</div>\n");
    html
}

fn reply_form(board_short: &str, thread_id: i64, csrf_token: &str) -> String {
    let image_mb = crate::config::CONFIG.max_image_size / 1024 / 1024;
    let video_mb = crate::config::CONFIG.max_video_size / 1024 / 1024;
    let audio_mb = crate::config::CONFIG.max_audio_size / 1024 / 1024;
    format!(
        r#"<div class="post-form-container reply-form-container">
<div class="post-form-title">[ reply to thread ]</div>
<form class="post-form" method="POST" action="/{board}/thread/{tid}" enctype="multipart/form-data">
  <input type="hidden" name="_csrf" value="{csrf}">
  <table>
    <tr><td>name</td>
        <td><input type="text" name="name" placeholder="Anonymous" maxlength="64"></td></tr>
    <tr><td>body</td>
        <td><textarea id="reply-body" name="body" rows="4" maxlength="4096"></textarea>
            <button type="submit">post reply</button></td></tr>
    <tr><td>file</td>
        <td><input type="file" name="file" accept="image/jpeg,image/png,image/gif,image/webp,video/mp4,video/webm,audio/mpeg,audio/ogg,audio/flac,audio/wav,audio/mp4,audio/aac,audio/webm,.mp3,.ogg,.flac,.wav,.m4a,.aac">
            <span style="font-size:0.72rem;color:var(--text-dim)">jpg/png/gif/webp · max {image_mb} MiB &nbsp;|&nbsp; mp4/webm · max {video_mb} MiB &nbsp;|&nbsp; mp3/ogg/flac/wav/m4a · max {audio_mb} MiB</span></td></tr>
    <tr><td>del token</td>
        <td><input type="text" name="deletion_token" placeholder="password to delete" maxlength="64"></td></tr>
  </table>
</form>
</div>"#,
        board = escape_html(board_short),
        tid = thread_id,
        csrf = escape_html(csrf_token),
        image_mb = image_mb,
        video_mb = video_mb,
        audio_mb = audio_mb,
    )
}

// ─── Catalog page ─────────────────────────────────────────────────────────────

pub fn catalog_page(
    board: &Board,
    threads: &[Thread],
    csrf_token: &str,
    boards: &[Board],
    collapse_greentext: bool,
) -> String {
    let bs = escape_html(&board.short_name);
    let bn = escape_html(&board.name);

    let mut body = format!(
        r#"<div class="board-header">
  <h1>/{bs}/  — {bn} — catalog</h1>
  <p class="board-desc">{desc}</p>
</div>
<div class="post-toggle-bar centered">
  <button class="post-toggle-btn" onclick="togglePostForm()">[ Start a New Thread ]</button>
</div>
<div class="post-form-wrap" id="post-form-wrap" style="display:none">
  {form}
</div>
<div class="catalog-grid">"#,
        bs = bs,
        bn = bn,
        desc = escape_html(&board.description),
        form = new_thread_form(&board.short_name, csrf_token),
    );

    for t in threads {
        let thumb_html = if let Some(th) = &t.op_thumb {
            format!(
                r#"<img class="catalog-thumb" src="/boards/{}" loading="lazy" alt="">"#,
                escape_html(th)
            )
        } else {
            r#"<div class="catalog-no-image">no img</div>"#.to_string()
        };

        let subject = t
            .subject
            .as_deref()
            .unwrap_or_else(|| t.op_body.as_deref().unwrap_or(""));
        let preview: String = subject.chars().take(80).collect();

        body.push_str(&format!(
            r#"<div class="catalog-item{sticky}">
<a href="/{board}/thread/{tid}">
{thumb}
<div class="catalog-info">
<span class="catalog-replies">{replies}R</span>
<p class="catalog-subject">{subj}</p>
</div>
</a>
</div>"#,
            sticky = if t.sticky { " sticky" } else { "" },
            board = escape_html(&board.short_name),
            tid = t.id,
            thumb = thumb_html,
            replies = t.reply_count,
            subj = escape_html(&preview),
        ));
    }

    body.push_str("</div>");
    body.push_str(TOGGLE_SCRIPT);
    base_layout(
        &format!("/{}/  catalog", board.short_name),
        Some(&board.short_name),
        &body,
        csrf_token,
        boards,
        collapse_greentext,
    )
}

// ─── Search results ───────────────────────────────────────────────────────────

pub fn search_page(
    board: &Board,
    query: &str,
    posts: &[Post],
    pagination: &Pagination,
    csrf_token: &str,
    boards: &[Board],
    collapse_greentext: bool,
) -> String {
    let mut body = format!(
        r#"<div class="page-box">
<h2 style="color:var(--green-pale);font-size:0.9rem;margin-bottom:8px">search: "{}" in /{}/</h2>
<form method="GET" action="/{}/search">
  <input type="text" name="q" value="{}" maxlength="64" style="background:var(--bg-input);border:1px solid var(--border);color:var(--green-pale);padding:4px 8px;font-family:var(--font)">
  <button type="submit">search</button>
</form>"#,
        escape_html(query),
        escape_html(&board.short_name),
        escape_html(&board.short_name),
        escape_html(query),
    );

    if posts.is_empty() {
        body.push_str(r#"<p style="color:var(--text-dim);margin-top:8px">no results found.</p>"#);
    } else {
        body.push_str(&format!(
            r#"<p style="color:var(--text-dim);font-size:0.8rem;margin-top:6px">{} result(s)</p>"#,
            pagination.total
        ));
        for post in posts {
            body.push_str(&render_post(
                post,
                &board.short_name,
                csrf_token,
                false,
                false,
                true,
            ));
        }
        body.push_str(&render_pagination(
            pagination,
            &format!(
                "/{}/search?q={}",
                board.short_name,
                urlencoding_simple(query)
            ),
        ));
    }

    body.push_str("</div>");
    base_layout(
        &format!("search — /{}/", board.short_name),
        Some(&board.short_name),
        &body,
        csrf_token,
        boards,
        collapse_greentext,
    )
}

// ─── Admin pages ──────────────────────────────────────────────────────────────

pub fn admin_login_page(error: Option<&str>, csrf_token: &str, boards: &[Board]) -> String {
    let err_html = error
        .map(|e| format!(r#"<div class="error">{}</div>"#, escape_html(e)))
        .unwrap_or_default();

    let body = format!(
        r#"<div class="page-box admin-login">
<h2>[ admin login ]</h2>
{err}
<form method="POST" action="/admin/login">
<input type="hidden" name="_csrf" value="{csrf}">
<table>
<tr><td>username</td><td><input type="text" name="username" autofocus required autocomplete="username"></td></tr>
<tr><td>password</td><td><input type="password" name="password" required autocomplete="current-password"></td></tr>
<tr><td></td><td><button type="submit">authenticate</button></td></tr>
</table>
</form>
</div>"#,
        err = err_html,
        csrf = escape_html(csrf_token),
    );
    base_layout("admin login", None, &body, csrf_token, boards, false)
}

pub fn admin_panel_page(
    boards: &[Board],
    bans: &[Ban],
    filters: &[WordFilter],
    collapse_greentext: bool,
    csrf_token: &str,
    full_backups: &[BackupInfo],
    board_backups: &[BackupInfo],
) -> String {
    let mut board_cards = String::new();
    for b in boards {
        let checked = |v: bool| if v { " checked" } else { "" };
        board_cards.push_str(&format!(
            r#"<details class="board-settings-card">
<summary>/{short}/ — {name} {nsfw_tag}</summary>
<form method="POST" action="/admin/board/settings" class="board-settings-form">
<input type="hidden" name="_csrf"     value="{csrf}">
<input type="hidden" name="board_id"  value="{id}">
<div class="board-settings-grid">
  <label>Name<input type="text" name="name" value="{name_raw}" maxlength="64" required></label>
  <label>Description<input type="text" name="description" value="{desc_raw}" maxlength="256"></label>
  <label>Bump limit<input type="number" name="bump_limit" value="{bump}" min="1" max="10000"></label>
  <label>Max threads<input type="number" name="max_threads" value="{maxt}" min="1" max="1000"></label>
</div>
<div class="board-settings-checks">
  <label><input type="checkbox" name="nsfw"            value="1"{nsfw_ck}> NSFW</label>
  <label><input type="checkbox" name="allow_images"    value="1"{img_ck}>  Allow images</label>
  <label><input type="checkbox" name="allow_video"     value="1"{vid_ck}>  Allow video</label>
  <label><input type="checkbox" name="allow_audio"     value="1"{aud_ck}>  Allow audio</label>
  <label><input type="checkbox" name="allow_tripcodes" value="1"{trip_ck}> Allow tripcodes</label>
</div>
<div class="board-settings-actions">
  <button type="submit">save settings</button>
</div>
</form>
<!-- FIX[LOW-10]: Delete form is now OUTSIDE the settings form.
     Nested <form> elements are invalid HTML per spec; browsers discard
     the inner form's association unpredictably. -->
<form method="POST" action="/admin/board/delete" style="display:inline;margin-top:4px">
  <input type="hidden" name="_csrf"     value="{csrf}">
  <input type="hidden" name="board_id"  value="{id}">
  <button type="submit" class="btn-danger"
          onclick="return confirm('Delete /{short}/ and ALL its content?')">delete board</button>
</form>
<a href="/admin/board/backup/{short}" style="display:inline-block;margin-left:0.5rem;margin-top:4px">
  <button type="button">&#8659; download to computer /{short}/</button>
</a>
<form method="POST" action="/admin/board/backup/create" style="display:inline-block;margin-left:0.25rem;margin-top:4px">
  <input type="hidden" name="_csrf" value="{csrf}">
  <input type="hidden" name="board_short" value="{short}">
  <button type="submit">&#128190; save to server /{short}/</button>
</form>
</details>"#,
            short = escape_html(&b.short_name),
            name = escape_html(&b.name),
            nsfw_tag = if b.nsfw { r#"<span class="tag nsfw-tag">NSFW</span>"# } else { "" },
            csrf = escape_html(csrf_token),
            id = b.id,
            name_raw = escape_html(&b.name),
            desc_raw = escape_html(&b.description),
            bump = b.bump_limit,
            maxt = b.max_threads,
            nsfw_ck = checked(b.nsfw),
            img_ck = checked(b.allow_images),
            vid_ck = checked(b.allow_video),
            aud_ck = checked(b.allow_audio),
            trip_ck = checked(b.allow_tripcodes),
        ));
    }

    let mut ban_rows = String::new();
    for ban in bans {
        let expires = ban
            .expires_at
            .map(fmt_ts)
            .unwrap_or_else(|| "permanent".to_string());
        ban_rows.push_str(&format!(
            r#"<tr>
<td class="ip-hash">{}</td><td>{}</td><td>{}</td>
<td>
<form method="POST" action="/admin/ban/remove" style="display:inline">
<input type="hidden" name="_csrf" value="{csrf}">
<input type="hidden" name="ban_id" value="{id}">
<button type="submit">lift</button>
</form>
</td>
</tr>"#,
            // FIX[MEDIUM-13]: Use .get(..16) instead of [..16] to avoid a panic
            // if ip_hash is somehow shorter than 16 chars (e.g. from a migrated DB).
            escape_html(ban.ip_hash.get(..16).unwrap_or(&ban.ip_hash)),
            escape_html(ban.reason.as_deref().unwrap_or("")),
            escape_html(&expires),
            csrf = escape_html(csrf_token),
            id = ban.id,
        ));
    }

    let mut filter_rows = String::new();
    for f in filters {
        filter_rows.push_str(&format!(
            r#"<tr>
<td>{}</td><td>{}</td>
<td>
<form method="POST" action="/admin/filter/remove" style="display:inline">
<input type="hidden" name="_csrf" value="{csrf}">
<input type="hidden" name="filter_id" value="{id}">
<button type="submit">remove</button>
</form>
</td>
</tr>"#,
            escape_html(&f.pattern),
            escape_html(&f.replacement),
            csrf = escape_html(csrf_token),
            id = f.id,
        ));
    }

    // ── Full backup file list ─────────────────────────────────────────────────
    let mut full_backup_rows = String::new();
    if full_backups.is_empty() {
        full_backup_rows.push_str(
            "<tr><td colspan=\"4\" style=\"color:var(--text-dim);text-align:center\">no backups yet</td></tr>",
        );
    }
    for bf in full_backups {
        let size_fmt = format_file_size(bf.size_bytes as i64);
        full_backup_rows.push_str(&format!(
            r#"<tr>
<td style="word-break:break-all">{fname}</td>
<td style="white-space:nowrap">{size}</td>
<td style="white-space:nowrap">{modified}</td>
<td style="white-space:nowrap">
  <a href="/admin/backup/download/full/{fname}" style="margin-right:0.4rem">&#8659; download to computer</a>
  <form method="POST" action="/admin/backup/restore-saved" style="display:inline;margin-right:0.4rem">
    <input type="hidden" name="_csrf" value="{csrf}">
    <input type="hidden" name="filename" value="{fname}">
    <button type="submit" onclick="return confirm('WARNING: Restore from {fname}? This will overwrite the live database and all uploads. Cannot be undone.')">&#8635; restore</button>
  </form>
  <form method="POST" action="/admin/backup/delete" style="display:inline">
    <input type="hidden" name="_csrf" value="{csrf}">
    <input type="hidden" name="kind" value="full">
    <input type="hidden" name="filename" value="{fname}">
    <button type="submit" class="btn-danger" onclick="return confirm('Delete {fname}? This cannot be undone.')">&#10005; delete</button>
  </form>
</td>
</tr>"#,
            fname = escape_html(&bf.filename),
            size = size_fmt,
            modified = escape_html(&bf.modified),
            csrf = escape_html(csrf_token),
        ));
    }

    // ── Board backup file list ────────────────────────────────────────────────
    let mut board_backup_rows = String::new();
    if board_backups.is_empty() {
        board_backup_rows.push_str(
            "<tr><td colspan=\"4\" style=\"color:var(--text-dim);text-align:center\">no board backups yet</td></tr>",
        );
    }
    for bf in board_backups {
        let size_fmt = format_file_size(bf.size_bytes as i64);
        board_backup_rows.push_str(&format!(
            r#"<tr>
<td style="word-break:break-all">{fname}</td>
<td style="white-space:nowrap">{size}</td>
<td style="white-space:nowrap">{modified}</td>
<td style="white-space:nowrap">
  <a href="/admin/backup/download/board/{fname}" style="margin-right:0.4rem">&#8659; download to computer</a>
  <form method="POST" action="/admin/board/backup/restore-saved" style="display:inline;margin-right:0.4rem">
    <input type="hidden" name="_csrf" value="{csrf}">
    <input type="hidden" name="filename" value="{fname}">
    <button type="submit" onclick="return confirm('WARNING: Restore board from {fname}? This will wipe and replace that board. Cannot be undone.')">&#8635; restore</button>
  </form>
  <form method="POST" action="/admin/backup/delete" style="display:inline">
    <input type="hidden" name="_csrf" value="{csrf}">
    <input type="hidden" name="kind" value="board">
    <input type="hidden" name="filename" value="{fname}">
    <button type="submit" class="btn-danger" onclick="return confirm('Delete {fname}? This cannot be undone.')">&#10005; delete</button>
  </form>
</td>
</tr>"#,
            fname = escape_html(&bf.filename),
            size = size_fmt,
            modified = escape_html(&bf.modified),
            csrf = escape_html(csrf_token),
        ));
    }

    let body = format!(
        r#"<div class="admin-panel">
<h1>[ admin panel ]</h1>
<form method="POST" action="/admin/logout">
<input type="hidden" name="_csrf" value="{csrf}">
<button type="submit">logout</button>
</form>

<section class="admin-section">
<h2>// boards</h2>
<div class="admin-board-cards">{board_cards}</div>
<h3>create board</h3>
<form method="POST" action="/admin/board/create">
<input type="hidden" name="_csrf" value="{csrf}">
<input type="text" name="short_name" placeholder="short (e.g. tech)" maxlength="8" required>
<input type="text" name="name" placeholder="full name" maxlength="64" required>
<input type="text" name="description" placeholder="description" maxlength="256">
<label style="color:var(--text-dim);font-size:0.8rem"><input type="checkbox" name="nsfw" value="1"> NSFW</label>
<button type="submit">create</button>
</form>
</section>

<section class="admin-section">
<h2>// active bans</h2>
<table class="admin-table">
<thead><tr><th>ip hash (partial)</th><th>reason</th><th>expires</th><th>action</th></tr></thead>
<tbody>{ban_rows}</tbody>
</table>
<h3>add ban</h3>
<form method="POST" action="/admin/ban/add">
<input type="hidden" name="_csrf" value="{csrf}">
<input type="text" name="ip_hash" placeholder="ip hash" required>
<input type="text" name="reason" placeholder="reason">
<input type="text" name="duration_hours" placeholder="hours (blank=perm)" style="width:120px">
<button type="submit">ban</button>
</form>
</section>

<section class="admin-section">
<h2>// word filters</h2>
<table class="admin-table">
<thead><tr><th>pattern</th><th>replacement</th><th>action</th></tr></thead>
<tbody>{filter_rows}</tbody>
</table>
<h3>add filter</h3>
<form method="POST" action="/admin/filter/add">
<input type="hidden" name="_csrf" value="{csrf}">
<input type="text" name="pattern" placeholder="pattern to match" required>
<input type="text" name="replacement" placeholder="replace with">
<button type="submit">add</button>
</form>
</section>

<section class="admin-section">
<h2>// site settings</h2>
<form method="POST" action="/admin/site/settings">
<input type="hidden" name="_csrf" value="{csrf}">
<div class="board-settings-checks" style="margin-bottom:0.75rem">
  <label title="When enabled, 3 or more consecutive greentext lines are wrapped in a collapsible block. Existing posts are not affected — only new posts use the current setting.">
    <input type="checkbox" name="collapse_greentext" value="1"{collapse_ck}>
    Collapse long greentext walls (3+ lines) into expandable blocks
  </label>
</div>
<button type="submit">save settings</button>
</form>
</section>

<section class="admin-section">
<h2>// backup &amp; restore</h2>
<p style="color:var(--text-dim);font-size:0.85rem">Full backups include the complete database and all uploaded files. <strong>Save to server</strong> stores the backup in <code>rustchan-data/full-backups/</code> on the server filesystem (listed below). <strong>Restore from local file</strong> uploads a zip from your computer.</p>
<div style="display:flex;gap:1rem;flex-wrap:wrap;align-items:center;margin-top:0.75rem;margin-bottom:0.75rem">
<form method="POST" action="/admin/backup/create">
<input type="hidden" name="_csrf" value="{csrf}">
<button type="submit">&#128190; save to server</button>
</form>
<form method="POST" action="/admin/restore" enctype="multipart/form-data" style="display:flex;gap:0.5rem;align-items:center;flex-wrap:wrap">
<input type="hidden" name="_csrf" value="{csrf}">
<input type="file" name="backup_file" accept=".zip" required style="color:var(--text)">
<button type="submit" class="btn-danger"
        onclick="return confirm('WARNING: This will overwrite the database and all uploaded files. Cannot be undone. Continue?')">&#8635; restore from local file</button>
</form>
</div>
<table style="width:100%;border-collapse:collapse;font-size:0.85rem">
<thead><tr style="color:var(--text-dim)"><th style="text-align:left">filename</th><th style="text-align:left">size</th><th style="text-align:left">created</th><th></th></tr></thead>
<tbody>{full_backup_rows}</tbody>
</table>
</section>

<section class="admin-section">
<h2>// board backup &amp; restore</h2>
<p style="color:var(--text-dim);font-size:0.85rem">Board backups cover a single board. Use <em>save to server</em> on a board card above to store the backup in <code>rustchan-data/board-backups/</code>, or use the table below to download, restore, or delete saved backups. <strong>Restore from local file</strong> uploads a zip from your computer.</p>
<div style="margin-top:0.5rem;margin-bottom:0.75rem">
<form method="POST" action="/admin/board/restore" enctype="multipart/form-data" style="display:flex;gap:0.5rem;align-items:center;flex-wrap:wrap">
<input type="hidden" name="_csrf" value="{csrf}">
<input type="file" name="backup_file" accept=".zip" required style="color:var(--text)">
<button type="submit" class="btn-danger"
        onclick="return confirm('WARNING: This will wipe and replace the board from the backup zip. Other boards are unaffected. Continue?')">&#8635; restore board from local file</button>
</form>
</div>
<table style="width:100%;border-collapse:collapse;font-size:0.85rem">
<thead><tr style="color:var(--text-dim)"><th style="text-align:left">filename</th><th style="text-align:left">size</th><th style="text-align:left">created</th><th></th></tr></thead>
<tbody>{board_backup_rows}</tbody>
</table>
</section>
</div>"#,
        csrf = escape_html(csrf_token),
        board_cards = board_cards,
        ban_rows = ban_rows,
        filter_rows = filter_rows,
        collapse_ck = if collapse_greentext { " checked" } else { "" },
        full_backup_rows = full_backup_rows,
        board_backup_rows = board_backup_rows,
    );

    base_layout("admin panel", None, &body, csrf_token, boards, false)
}

// ─── Error page ───────────────────────────────────────────────────────────────

pub fn error_page(code: u16, message: &str) -> String {
    format!(
        r#"<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Error {code}</title>
<link rel="stylesheet" href="/static/style.css">
</head>
<body>
<div class="page-box error-page">
<h1>error {code}</h1>
<p>{message}</p>
<p><a href="/">return home</a></p>
</div>
</body>
</html>"#,
        code = code,
        message = escape_html(message),
    )
}

// ─── Pagination helper ────────────────────────────────────────────────────────

fn render_pagination(p: &Pagination, base_url: &str) -> String {
    if p.total_pages() <= 1 {
        return String::new();
    }
    let sep = if base_url.contains('?') { "&" } else { "?" };
    let mut html = String::from(r#"<div class="pagination">"#);

    if p.has_prev() {
        html.push_str(&format!(
            r#"<a href="{}{sep}page={}">[prev]</a> "#,
            base_url,
            p.page - 1,
            sep = sep
        ));
    }
    html.push_str(&format!("page {} / {}", p.page, p.total_pages()));
    if p.has_next() {
        html.push_str(&format!(
            r#" <a href="{}{sep}page={}">[next]</a>"#,
            base_url,
            p.page + 1,
            sep = sep
        ));
    }

    html.push_str("</div>");
    html
}

// FIX[LOW-9]: Encode each UTF-8 *byte*, not each Unicode codepoint.
// RFC 3986 percent-encoding operates on bytes. The original implementation
// encoded e.g. 'é' (U+00E9) as %E9 instead of the correct %C3%A9
// (two UTF-8 bytes: 0xC3, 0xA9), producing malformed URLs for non-ASCII input.
fn urlencoding_simple(s: &str) -> String {
    let mut out = String::with_capacity(s.len() * 3);
    for &byte in s.as_bytes() {
        match byte {
            b'A'..=b'Z' | b'a'..=b'z' | b'0'..=b'9' | b'-' | b'_' | b'.' | b'~' => {
                out.push(byte as char)
            }
            b' ' => out.push('+'),
            b => out.push_str(&format!("%{:02X}", b)),
        }
    }
    out
}
