/**
 * Local-only macOS workaround for Playwright issue #42768.
 *
 * On macOS 27, a machine with Firefox installed has a TCC-protected
 * `~/Library/Application Support/Firefox` app-data directory. Playwright's
 * bundled Firefox resolves its app-data directory to that same path (the
 * bundled build is branded `Name=Firefox`, `Vendor=Mozilla`), so Gecko cannot
 * create its profile and every launch fails with:
 *
 *   "Could not find profile folder."
 *
 * This affects every stock Playwright build through 1.63.x. The upstream fix
 * carries the `v1.64` milestone; once a supported Playwright release contains
 * it, this shim and `RUSTCHAN_FIREFOX_REBRAND` must be deleted.
 *
 * The shim copies the installed Playwright Firefox bundle into the ignored
 * `output/playwright/firefox-rebranded/` directory, rewrites the app identity
 * to `Name=PlaywrightFirefox` / `Vendor=Playwright` in a
 * `Contents/Resources/browser/application.ini`, and launches the copy through
 * that `-app` descriptor. Gecko then resolves an app-data directory of its own
 * instead of the protected Firefox one. The browser revision is untouched
 * (no downgrade, no pin), and tests still execute on real Playwright Firefox.
 *
 * Opt in explicitly with `RUSTCHAN_FIREFOX_REBRAND=1`. The default launch path
 * is intentionally left unchanged so a broken host keeps failing loudly rather
 * than being silently patched.
 */
import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { firefox } from '@playwright/test';

const repoRoot = path.resolve(__dirname, '../..');
const workDir = path.join(repoRoot, 'output/playwright/firefox-rebranded');
const targetBundle = path.join(workDir, 'NightlyRebranded.app');
const wrapperPath = path.join(workDir, 'firefox-rebranded.sh');
const stampPath = path.join(workDir, 'source.stamp');

function copyBundle(sourceBundle: string): void {
  fs.rmSync(targetBundle, { recursive: true, force: true });
  fs.mkdirSync(workDir, { recursive: true });
  const copy = spawnSync('/bin/cp', ['-R', sourceBundle, targetBundle], { stdio: 'pipe' });
  if (copy.status !== 0) {
    throw new Error(
      `RUSTCHAN_FIREFOX_REBRAND: could not copy ${sourceBundle} to ${targetBundle}: ${copy.stderr?.toString() ?? 'unknown error'}`,
    );
  }
}

function rebrandApplicationIni(contents: string): string {
  const patched = contents
    .replace(/^Name=Firefox$/m, 'Name=PlaywrightFirefox')
    .replace(/^Vendor=Mozilla$/m, 'Vendor=Playwright');
  if (!patched.includes('Name=PlaywrightFirefox') || !patched.includes('Vendor=Playwright')) {
    throw new Error(
      'RUSTCHAN_FIREFOX_REBRAND: the bundled application.ini no longer contains the expected Firefox/Mozilla identity lines',
    );
  }
  return patched;
}

/** Materialize the rebranded bundle once per installed browser revision. */
function ensureRebrandedBundle(): string {
  let browserExecutable: string;
  try {
    browserExecutable = firefox.executablePath();
  } catch (error) {
    throw new Error(
      `RUSTCHAN_FIREFOX_REBRAND=1 requires the Playwright Firefox build. Run "npx playwright install firefox" first. (${String(error)})`,
    );
  }
  const sourceBundle = path.resolve(path.dirname(browserExecutable), '..', '..');
  const sourceIni = path.join(sourceBundle, 'Contents/Resources/application.ini');
  const stamp = `${browserExecutable}:${fs.statSync(browserExecutable).mtimeMs}`;

  if (fs.existsSync(stampPath) && fs.readFileSync(stampPath, 'utf8') === stamp && fs.existsSync(wrapperPath)) {
    return wrapperPath;
  }

  copyBundle(sourceBundle);
  const patchedIni = rebrandApplicationIni(fs.readFileSync(sourceIni, 'utf8'));
  const browserIni = path.join(targetBundle, 'Contents/Resources/browser/application.ini');
  fs.mkdirSync(path.dirname(browserIni), { recursive: true });
  fs.writeFileSync(browserIni, patchedIni);

  const targetExecutable = path.join(targetBundle, 'Contents/MacOS/firefox');
  fs.writeFileSync(
    wrapperPath,
    `#!/bin/sh\n# Generated by tests/e2e/firefox-rebrand.ts for Playwright #42768.\nexec "${targetExecutable}" -app "${browserIni}" "$@"\n`,
  );
  fs.chmodSync(wrapperPath, 0o755);
  fs.writeFileSync(stampPath, stamp);
  return wrapperPath;
}

/**
 * Returns the executable override for the Firefox projects when
 * `RUSTCHAN_FIREFOX_REBRAND=1` is set on macOS, or `undefined` for the default
 * launch path.
 */
export function rebrandedFirefoxExecutable(): string | undefined {
  if (process.env.RUSTCHAN_FIREFOX_REBRAND !== '1') return undefined;
  if (process.platform !== 'darwin') {
    throw new Error(
      'RUSTCHAN_FIREFOX_REBRAND=1 is a macOS-only workaround for Playwright issue #42768. Do not set it on this platform.',
    );
  }
  return ensureRebrandedBundle();
}
