// media/ffmpeg.rs
//
// FFmpeg binary detection and subprocess execution helpers.
//
// Design notes:
//   • Detection is done by running `ffmpeg -version` and checking the exit code.
//   • All subprocess invocations use `std::process::Command` with explicit
//     argument arrays — never shell strings — to eliminate injection surfaces.
//   • This module is called from synchronous contexts (spawn_blocking), so
//     std::process::Command is used instead of tokio::process::Command.
//   • Temp files passed to ffmpeg are created by the caller; this module only
//     executes the subprocess and reports success or failure.
//   • If ffmpeg exits non-zero, the error includes the trimmed stderr so
//     operators can diagnose codec or format issues without reading raw logs.

use anyhow::{Context, Result};
use std::borrow::Cow;
use std::path::Path;
use std::process::{Command, Stdio};
use std::sync::LazyLock;
use std::thread;
use std::time::{Duration, Instant};

fn ffmpeg_command() -> Command {
    Command::new(&crate::config::CONFIG.ffmpeg_path)
}

fn ffprobe_command() -> Command {
    Command::new(&crate::config::CONFIG.ffprobe_path)
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum StreamKind {
    AudioOnly,
    Video,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Vp9EncodingProfile {
    pub cpu_used: u8,
    pub tile_columns: u8,
    pub threads: usize,
    pub row_mt: bool,
    pub label: Cow<'static, str>,
}

static ENCODER_LIST: LazyLock<Option<String>> = LazyLock::new(|| {
    ffmpeg_command()
        .args(["-encoders"])
        .stdout(Stdio::piped())
        .stderr(Stdio::null())
        .output()
        .ok()
        .map(|output| String::from_utf8_lossy(&output.stdout).into_owned())
});

/// Probe whether the `ffmpeg` binary is reachable on the current PATH.
///
/// Runs `ffmpeg -version` and returns `true` if the process exits successfully.
/// This is a synchronous, blocking call and is intended to be invoked at
/// startup (or lazily on first upload) inside a `spawn_blocking` task.
///
/// A `false` return means conversion and video-thumbnail features will be
/// unavailable; all callers must degrade gracefully.
#[must_use]
pub fn detect_ffmpeg() -> bool {
    ffmpeg_command()
        .arg("-version")
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status()
        .map(|s| s.success())
        .unwrap_or(false)
}

/// Execute `ffmpeg` with the given argument slice.
///
/// All arguments must be pre-constructed, static strings — no user-supplied
/// data may appear in `args` directly.  File paths passed to ffmpeg must be
/// UUID-based names generated by the server.
///
/// Returns `Ok(())` on exit code 0, or an `Err` containing the trimmed
/// stderr output on any non-zero exit.
///
/// # Errors
/// Returns an error if ffmpeg cannot be spawned (binary missing, permission
/// denied) or if the process exits with a non-zero status code.
pub fn run_ffmpeg(args: &[&str]) -> Result<()> {
    let output = run_command_with_timeout(
        ffmpeg_command().args(args),
        &crate::config::CONFIG.ffmpeg_path,
        "ffmpeg",
    )?;

    if output.status.success() {
        Ok(())
    } else {
        Err(anyhow::anyhow!(
            "ffmpeg exited with {}: {}",
            output.status,
            String::from_utf8_lossy(&output.stderr).trim()
        ))
    }
}

/// Convert an image file to WebP using ffmpeg.
///
/// Uses quality 85 and strips all metadata (`-map_metadata -1`).
/// Input can be any format ffmpeg understands (JPEG, PNG, BMP, TIFF, GIF, …).
///
/// The `-loop 0` flag causes multi-frame inputs (GIF) to produce an animated
/// WebP that loops forever, matching the default GIF behaviour.  For
/// single-frame inputs ffmpeg silently ignores the flag.
///
/// # Errors
/// Returns an error if ffmpeg exits non-zero or cannot be spawned.
pub fn ffmpeg_image_to_webp(input: &Path, output: &Path) -> Result<()> {
    let in_str = path_to_str(input)?;
    let out_str = path_to_str(output)?;

    run_ffmpeg(&[
        "-loglevel",
        "error",
        "-i",
        in_str,
        "-c:v",
        "libwebp",
        "-quality",
        "85",
        "-loop",
        "0",
        "-map_metadata",
        "-1",
        "-y",
        out_str,
    ])
    .with_context(|| format!("image→webp conversion failed for {in_str}"))
}

/// Convert an animated image file to WebP while scaling to fit within the
/// supplied banner bounds.
/// Convert an input image to animated WebP while scaling to fit a max box.
///
/// # Errors
/// Returns an error if ffmpeg is unavailable or the conversion fails.
pub fn ffmpeg_image_to_webp_scaled(
    input: &Path,
    output: &Path,
    max_width: u32,
    max_height: u32,
) -> Result<()> {
    let in_str = path_to_str(input)?;
    let out_str = path_to_str(output)?;
    let scale = format!(
        "scale='if(gt(iw,ih),min(iw,{max_width}),-2)':'if(gt(iw,ih),-2,min(ih,{max_height}))'"
    );

    run_ffmpeg(&[
        "-loglevel",
        "error",
        "-i",
        in_str,
        "-vf",
        &scale,
        "-c:v",
        "libwebp",
        "-quality",
        "85",
        "-loop",
        "0",
        "-map_metadata",
        "-1",
        "-y",
        out_str,
    ])
    .with_context(|| format!("image→webp conversion failed for {in_str}"))
}

/// Generate a WebP thumbnail from an image or video by extracting the first
/// frame and scaling to fit within `max_dim × max_dim`.
///
/// The `-2` height modifier ensures the scaled height is rounded to an even
/// number, required by many video codecs.  Aspect ratio is always preserved.
/// Thumbnail quality is fixed at 80 per project spec.
///
/// Works for both static images and video/animation sources.
///
/// # Errors
/// Returns an error if ffmpeg exits non-zero or cannot be spawned.
pub fn ffmpeg_thumbnail(input: &Path, output: &Path, max_dim: u32) -> Result<()> {
    let in_str = path_to_str(input)?;
    let out_str = path_to_str(output)?;
    let scale = format!("scale='if(gt(iw,ih),{max_dim},-2)':'if(gt(iw,ih),-2,{max_dim})'");

    run_ffmpeg(&[
        "-loglevel",
        "error",
        "-i",
        in_str,
        "-vframes",
        "1",
        "-vf",
        &scale,
        "-c:v",
        "libwebp",
        "-quality",
        "80",
        "-y",
        out_str,
    ])
    .with_context(|| format!("thumbnail generation failed for {in_str}"))
}

/// Probe whether a `WebM` container is audio-only or contains video streams.
///
/// # Errors
/// Returns an error if `ffprobe` cannot be spawned, times out, exits non-zero,
/// or reports no audio/video streams.
pub fn probe_stream_kind(path: &Path) -> Result<StreamKind> {
    let path_str = path_to_str(path)?;
    let output = run_command_with_timeout(
        ffprobe_command().args([
            "-v",
            "quiet",
            "-show_entries",
            "stream=codec_type",
            "-of",
            "default=noprint_wrappers=1:nokey=1",
            path_str,
        ]),
        &crate::config::CONFIG.ffprobe_path,
        "ffprobe",
    )?;

    if !output.status.success() {
        return Err(anyhow::anyhow!(
            "ffprobe exited with {}: {}",
            output.status,
            String::from_utf8_lossy(&output.stderr).trim()
        ));
    }

    let mut saw_audio = false;
    for line in String::from_utf8_lossy(&output.stdout).lines() {
        match line.trim() {
            "video" => return Ok(StreamKind::Video),
            "audio" => saw_audio = true,
            _ => {}
        }
    }

    if saw_audio {
        Ok(StreamKind::AudioOnly)
    } else {
        Err(anyhow::anyhow!(
            "ffprobe returned no audio or video streams for: {path_str}"
        ))
    }
}

/// Probe the primary video codec of a media file using `ffprobe`.
///
/// Returns the lowercase codec name (e.g. `"vp9"`, `"av1"`, `"h264"`) on
/// success.  `ffprobe` must be on the same PATH as `ffmpeg`.
///
/// # Errors
/// Returns an error if `ffprobe` cannot be spawned, exits non-zero, or its
/// output contains no recognisable codec name.
pub fn probe_video_codec(path: &str) -> Result<String> {
    let output = run_command_with_timeout(
        ffprobe_command().args([
            "-v",
            "quiet",
            "-select_streams",
            "v:0",
            "-show_entries",
            "stream=codec_name",
            "-of",
            "default=noprint_wrappers=1:nokey=1",
            path,
        ]),
        &crate::config::CONFIG.ffprobe_path,
        "ffprobe",
    )?;

    if !output.status.success() {
        return Err(anyhow::anyhow!(
            "ffprobe exited with {}: {}",
            output.status,
            String::from_utf8_lossy(&output.stderr).trim()
        ));
    }

    let codec = String::from_utf8_lossy(&output.stdout)
        .trim()
        .to_ascii_lowercase();

    if codec.is_empty() {
        return Err(anyhow::anyhow!(
            "ffprobe returned no codec name for: {path}"
        ));
    }

    Ok(codec)
}

#[must_use]
pub fn vp9_encoding_profile() -> &'static Vp9EncodingProfile {
    static PROFILE: LazyLock<Vp9EncodingProfile> = LazyLock::new(detect_vp9_encoding_profile);
    &PROFILE
}

#[must_use]
pub fn build_vp9_transcode_args(input: &str, output: &str) -> Vec<String> {
    let profile = vp9_encoding_profile();
    let cpu_used = profile.cpu_used.to_string();
    let tile_columns = profile.tile_columns.to_string();
    let threads = profile.threads.to_string();
    let mut args = Vec::with_capacity(28);
    args.extend(
        [
            "-loglevel",
            "error",
            "-i",
            input,
            "-c:v",
            "libvpx-vp9",
            "-deadline",
            "good",
            "-cpu-used",
        ]
        .into_iter()
        .map(str::to_string),
    );
    args.push(cpu_used);
    args.extend(
        [
            "-row-mt",
            if profile.row_mt { "1" } else { "0" },
            "-tile-columns",
        ]
        .into_iter()
        .map(str::to_string),
    );
    args.push(tile_columns);
    args.extend(
        [
            "-threads",
            &threads,
            "-crf",
            "30",
            "-b:v",
            "0",
            "-pix_fmt",
            "yuv420p",
            "-c:a",
            "libopus",
            "-b:a",
            "128k",
            "-map_metadata",
            "-1",
            "-y",
            output,
        ]
        .into_iter()
        .map(str::to_string),
    );
    args
}
// ─── Internal helpers ──────────────────────────────────────────────────────────

fn detect_vp9_encoding_profile() -> Vp9EncodingProfile {
    let threads = std::thread::available_parallelism()
        .map(std::num::NonZeroUsize::get)
        .unwrap_or(1)
        .clamp(1, 16);

    let tile_columns = match threads {
        0..=2 => 0,
        3..=4 => 1,
        _ => 2,
    };

    #[cfg(any(target_arch = "x86", target_arch = "x86_64"))]
    {
        if std::arch::is_x86_feature_detected!("avx512f") {
            return Vp9EncodingProfile {
                cpu_used: 1,
                tile_columns,
                threads,
                row_mt: true,
                label: Cow::Borrowed("x86-avx512"),
            };
        }
        if std::arch::is_x86_feature_detected!("avx2") {
            return Vp9EncodingProfile {
                cpu_used: 2,
                tile_columns,
                threads,
                row_mt: true,
                label: Cow::Borrowed("x86-avx2"),
            };
        }
        if std::arch::is_x86_feature_detected!("avx") {
            return Vp9EncodingProfile {
                cpu_used: 3,
                tile_columns: tile_columns.min(1),
                threads,
                row_mt: true,
                label: Cow::Borrowed("x86-avx"),
            };
        }
        if std::arch::is_x86_feature_detected!("sse4.1") {
            return Vp9EncodingProfile {
                cpu_used: 4,
                tile_columns: tile_columns.min(1),
                threads: threads.min(8),
                row_mt: true,
                label: Cow::Borrowed("x86-sse4.1"),
            };
        }
    }

    #[cfg(target_arch = "aarch64")]
    {
        Vp9EncodingProfile {
            cpu_used: 3,
            tile_columns: tile_columns.min(1),
            threads,
            row_mt: true,
            label: Cow::Borrowed("aarch64-neon"),
        }
    }

    #[cfg(target_arch = "arm")]
    {
        return Vp9EncodingProfile {
            cpu_used: 4,
            tile_columns: 0,
            threads: threads.min(4),
            row_mt: true,
            label: Cow::Borrowed("arm"),
        };
    }

    #[cfg(not(any(target_arch = "aarch64", target_arch = "arm")))]
    {
        Vp9EncodingProfile {
            cpu_used: 4,
            tile_columns: 0,
            threads: threads.min(4),
            row_mt: false,
            label: Cow::Owned(format!("generic-{}", std::env::consts::ARCH)),
        }
    }
}

/// Convert a `Path` to a UTF-8 `&str`, returning a descriptive error if the
/// path contains non-UTF-8 bytes (rare on all supported platforms).
fn path_to_str(p: &Path) -> Result<&str> {
    p.to_str()
        .ok_or_else(|| anyhow::anyhow!("path contains non-UTF-8 characters: {}", p.display()))
}

fn run_command_with_timeout(
    command: &mut Command,
    program: &str,
    label: &str,
) -> Result<std::process::Output> {
    let timeout = Duration::from_secs(crate::config::CONFIG.ffmpeg_timeout_secs);
    let mut child = command
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .with_context(|| {
            format!("failed to spawn {label} binary '{program}' — is it installed and executable?")
        })?;
    let started = Instant::now();

    loop {
        if child.try_wait()?.is_some() {
            return child
                .wait_with_output()
                .with_context(|| format!("{label} I/O error"));
        }
        if started.elapsed() >= timeout {
            let _ = child.kill();
            let _ = child.wait();
            return Err(anyhow::anyhow!(
                "{label} timed out after {}s",
                timeout.as_secs()
            ));
        }
        thread::sleep(Duration::from_millis(50));
    }
}

/// Probe whether the current ffmpeg binary has the `libwebp` encoder compiled in.
///
/// Runs `ffmpeg -encoders` and scans stdout for a line containing `libwebp`.
/// Returns `true` only when ffmpeg is present AND the encoder is available.
///
/// This is a synchronous, blocking call intended for use at server startup
/// inside a `spawn_blocking` task, or called directly from the startup path
/// where blocking is acceptable.
#[must_use]
pub fn check_webp_encoder() -> bool {
    ENCODER_LIST
        .as_deref()
        .is_some_and(|stdout| stdout.lines().any(|line| line.contains("libwebp")))
}

/// Probe whether the current ffmpeg binary has the `libvpx-vp9` encoder compiled in.
///
/// Required for MP4→WebM and WebM/AV1→WebM/VP9 transcoding.  Runs
/// `ffmpeg -encoders` and scans stdout for a line containing `libvpx-vp9`.
/// Returns `true` only when ffmpeg is present AND the encoder is available.
///
/// This is a synchronous, blocking call intended for use at server startup.
#[must_use]
pub fn check_vp9_encoder() -> bool {
    ENCODER_LIST
        .as_deref()
        .is_some_and(|stdout| stdout.lines().any(|line| line.contains("libvpx-vp9")))
}

/// Probe whether the current ffmpeg binary has the `libopus` encoder compiled in.
///
/// Required for audio encoding during MP4→WebM and WebM/AV1→WebM/VP9 transcoding.
/// Runs `ffmpeg -encoders` and scans stdout for a line containing `libopus`.
/// Returns `true` only when ffmpeg is present AND the encoder is available.
///
/// This is a synchronous, blocking call intended for use at server startup.
#[must_use]
pub fn check_opus_encoder() -> bool {
    ENCODER_LIST
        .as_deref()
        .is_some_and(|stdout| stdout.lines().any(|line| line.contains("libopus")))
}

#[cfg(test)]
mod tests {
    use super::build_vp9_transcode_args;

    #[test]
    fn vp9_transcode_args_include_platform_tuning_flags() {
        let args = build_vp9_transcode_args("input.mp4", "output.webm");
        assert!(args.windows(2).any(|w| w == ["-c:v", "libvpx-vp9"]));
        assert!(args.windows(2).any(|w| w == ["-deadline", "good"]));
        assert!(args
            .windows(2)
            .any(|w| w == ["-row-mt", "1"] || w == ["-row-mt", "0"]));
        assert!(args
            .windows(2)
            .any(|w| w.first().is_some_and(|flag| flag == "-cpu-used")));
        assert!(args
            .windows(2)
            .any(|w| w.first().is_some_and(|flag| flag == "-tile-columns")));
        assert!(args
            .windows(2)
            .any(|w| w.first().is_some_and(|flag| flag == "-threads")));
        assert!(args.windows(2).any(|w| w == ["-pix_fmt", "yuv420p"]));
    }
}
