// media/ffmpeg.rs
//
// FFmpeg binary detection and subprocess execution helpers.
//
// Design notes:
//   • Detection is done by running `ffmpeg -version` and checking the exit code.
//   • All subprocess invocations use `std::process::Command` with explicit
//     argument arrays — never shell strings — to eliminate injection surfaces.
//   • This module is called from synchronous contexts (spawn_blocking), so
//     std::process::Command is used instead of tokio::process::Command.
//   • Temp files passed to ffmpeg are created by the caller; this module only
//     executes the subprocess and reports success or failure.
//   • If ffmpeg exits non-zero, the error includes the trimmed stderr so
//     operators can diagnose codec or format issues without reading raw logs.

use anyhow::{Context, Result};
use std::path::Path;
use std::process::{Command, Stdio};

/// Probe whether the `ffmpeg` binary is reachable on the current PATH.
///
/// Runs `ffmpeg -version` and returns `true` if the process exits successfully.
/// This is a synchronous, blocking call and is intended to be invoked at
/// startup (or lazily on first upload) inside a `spawn_blocking` task.
///
/// A `false` return means conversion and video-thumbnail features will be
/// unavailable; all callers must degrade gracefully.
#[must_use]
pub fn detect_ffmpeg() -> bool {
    Command::new("ffmpeg")
        .arg("-version")
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status()
        .map(|s| s.success())
        .unwrap_or(false)
}

/// Execute `ffmpeg` with the given argument slice.
///
/// All arguments must be pre-constructed, static strings — no user-supplied
/// data may appear in `args` directly.  File paths passed to ffmpeg must be
/// UUID-based names generated by the server.
///
/// Returns `Ok(())` on exit code 0, or an `Err` containing the trimmed
/// stderr output on any non-zero exit.
///
/// # Errors
/// Returns an error if ffmpeg cannot be spawned (binary missing, permission
/// denied) or if the process exits with a non-zero status code.
pub fn run_ffmpeg(args: &[&str]) -> Result<()> {
    let output = Command::new("ffmpeg")
        .args(args)
        .output()
        .context("failed to spawn ffmpeg — is it installed and on PATH?")?;

    if output.status.success() {
        Ok(())
    } else {
        Err(anyhow::anyhow!(
            "ffmpeg exited with {}: {}",
            output.status,
            String::from_utf8_lossy(&output.stderr).trim()
        ))
    }
}

/// Convert an image file to WebP using ffmpeg.
///
/// Uses quality 85 and strips all metadata (`-map_metadata -1`).
/// Input can be any format ffmpeg understands (JPEG, PNG, BMP, TIFF, GIF, …).
///
/// The `-loop 0` flag causes multi-frame inputs (GIF) to produce an animated
/// WebP that loops forever, matching the default GIF behaviour.  For
/// single-frame inputs ffmpeg silently ignores the flag.
///
/// # Errors
/// Returns an error if ffmpeg exits non-zero or cannot be spawned.
pub fn ffmpeg_image_to_webp(input: &Path, output: &Path) -> Result<()> {
    let in_str = path_to_str(input)?;
    let out_str = path_to_str(output)?;

    run_ffmpeg(&[
        "-loglevel",
        "error",
        "-i",
        in_str,
        "-c:v",
        "libwebp",
        "-quality",
        "85",
        "-loop",
        "0",
        "-map_metadata",
        "-1",
        "-y",
        out_str,
    ])
    .with_context(|| format!("image→webp conversion failed for {in_str}"))
}

/// Convert a GIF animation to `WebM` (VP9 codec) using ffmpeg.
///
/// Retained for potential future use but no longer called by the conversion
/// pipeline — GIFs are now converted to animated WebP via
/// [`ffmpeg_image_to_webp`] so they remain in the Image media category and
/// render as `<img>` tags rather than `<video>` tags.
///
/// # Errors
/// Returns an error if ffmpeg exits non-zero or cannot be spawned.
#[allow(dead_code)]
pub fn ffmpeg_gif_to_webm(input: &Path, output: &Path) -> Result<()> {
    let in_str = path_to_str(input)?;
    let out_str = path_to_str(output)?;

    run_ffmpeg(&[
        "-loglevel",
        "error",
        "-i",
        in_str,
        "-c:v",
        "libvpx-vp9",
        "-crf",
        "30",
        "-b:v",
        "0",
        "-map_metadata",
        "-1",
        "-y",
        out_str,
    ])
    .with_context(|| format!("gif→webm conversion failed for {in_str}"))
}

/// Generate a WebP thumbnail from an image or video by extracting the first
/// frame and scaling to fit within `max_dim × max_dim`.
///
/// The `-2` height modifier ensures the scaled height is rounded to an even
/// number, required by many video codecs.  Aspect ratio is always preserved.
/// Thumbnail quality is fixed at 80 per project spec.
///
/// Works for both static images and video/animation sources.
///
/// # Errors
/// Returns an error if ffmpeg exits non-zero or cannot be spawned.
pub fn ffmpeg_thumbnail(input: &Path, output: &Path, max_dim: u32) -> Result<()> {
    let in_str = path_to_str(input)?;
    let out_str = path_to_str(output)?;
    let scale = format!("scale='if(gt(iw,ih),{max_dim},-2)':'if(gt(iw,ih),-2,{max_dim})'");

    run_ffmpeg(&[
        "-loglevel",
        "error",
        "-i",
        in_str,
        "-vframes",
        "1",
        "-vf",
        &scale,
        "-c:v",
        "libwebp",
        "-quality",
        "80",
        "-y",
        out_str,
    ])
    .with_context(|| format!("thumbnail generation failed for {in_str}"))
}

/// Probe the primary video codec of a media file using `ffprobe`.
///
/// Returns the lowercase codec name (e.g. `"vp9"`, `"av1"`, `"h264"`) on
/// success.  `ffprobe` must be on the same PATH as `ffmpeg`.
///
/// # Errors
/// Returns an error if `ffprobe` cannot be spawned, exits non-zero, or its
/// output contains no recognisable codec name.
pub fn probe_video_codec(path: &str) -> Result<String> {
    let output = std::process::Command::new("ffprobe")
        .args([
            "-v",
            "quiet",
            "-select_streams",
            "v:0",
            "-show_entries",
            "stream=codec_name",
            "-of",
            "default=noprint_wrappers=1:nokey=1",
            path,
        ])
        .output()
        .context("failed to spawn ffprobe — is it installed and on PATH?")?;

    if !output.status.success() {
        return Err(anyhow::anyhow!(
            "ffprobe exited with {}: {}",
            output.status,
            String::from_utf8_lossy(&output.stderr).trim()
        ));
    }

    let codec = String::from_utf8_lossy(&output.stdout)
        .trim()
        .to_ascii_lowercase();

    if codec.is_empty() {
        return Err(anyhow::anyhow!(
            "ffprobe returned no codec name for: {path}"
        ));
    }

    Ok(codec)
}

/// Transcode a video file to `WebM` (VP9 video + Opus audio) using ffmpeg.
///
/// Uses constant-quality VP9 encoding (`-crf 30 -b:v 0`) and Opus audio at
/// 128 kbps.  All metadata is stripped.  Accepts MP4 or AV1 `WebM` inputs.
///
/// # Errors
/// Returns an error if ffmpeg exits non-zero or cannot be spawned.
pub fn ffmpeg_transcode_to_webm(input: &Path, output: &Path) -> Result<()> {
    let in_str = path_to_str(input)?;
    let out_str = path_to_str(output)?;

    run_ffmpeg(&[
        "-loglevel",
        "error",
        "-i",
        in_str,
        "-c:v",
        "libvpx-vp9",
        "-crf",
        "30",
        "-b:v",
        "0",
        "-c:a",
        "libopus",
        "-b:a",
        "128k",
        "-map_metadata",
        "-1",
        "-y",
        out_str,
    ])
    .with_context(|| format!("video→webm transcode failed for {in_str}"))
}

/// Generate a waveform PNG image for an audio file using ffmpeg's
/// `showwavespic` filter.
///
/// The output image will be `width × height` pixels.  The waveform is
/// rendered in a neutral grey (`0x888888`) suitable for both light and dark
/// page themes.
///
/// # Errors
/// Returns an error if ffmpeg exits non-zero or cannot be spawned.
pub fn ffmpeg_audio_waveform(input: &Path, output: &Path, width: u32, height: u32) -> Result<()> {
    let in_str = path_to_str(input)?;
    let out_str = path_to_str(output)?;
    let filter = format!("showwavespic=s={width}x{height}:colors=0x888888");

    run_ffmpeg(&[
        "-loglevel",
        "error",
        "-i",
        in_str,
        "-filter_complex",
        &filter,
        "-frames:v",
        "1",
        "-y",
        out_str,
    ])
    .with_context(|| format!("audio waveform generation failed for {in_str}"))
}

// ─── Internal helpers ──────────────────────────────────────────────────────────

/// Convert a `Path` to a UTF-8 `&str`, returning a descriptive error if the
/// path contains non-UTF-8 bytes (rare on all supported platforms).
fn path_to_str(p: &Path) -> Result<&str> {
    p.to_str()
        .ok_or_else(|| anyhow::anyhow!("path contains non-UTF-8 characters: {}", p.display()))
}

/// Probe whether the current ffmpeg binary has the `libwebp` encoder compiled in.
///
/// Runs `ffmpeg -encoders` and scans stdout for a line containing `libwebp`.
/// Returns `true` only when ffmpeg is present AND the encoder is available.
///
/// This is a synchronous, blocking call intended for use at server startup
/// inside a `spawn_blocking` task, or called directly from the startup path
/// where blocking is acceptable.
#[must_use]
pub fn check_webp_encoder() -> bool {
    let output = Command::new("ffmpeg")
        .args(["-encoders"])
        .stdout(Stdio::piped())
        .stderr(Stdio::null())
        .output();

    match output {
        Ok(o) => {
            let stdout = String::from_utf8_lossy(&o.stdout);
            stdout.lines().any(|line| line.contains("libwebp"))
        }
        Err(_) => false,
    }
}

/// Probe whether the current ffmpeg binary has the `libvpx-vp9` encoder compiled in.
///
/// Required for MP4→WebM and WebM/AV1→WebM/VP9 transcoding.  Runs
/// `ffmpeg -encoders` and scans stdout for a line containing `libvpx-vp9`.
/// Returns `true` only when ffmpeg is present AND the encoder is available.
///
/// This is a synchronous, blocking call intended for use at server startup.
#[must_use]
pub fn check_vp9_encoder() -> bool {
    let output = Command::new("ffmpeg")
        .args(["-encoders"])
        .stdout(Stdio::piped())
        .stderr(Stdio::null())
        .output();

    match output {
        Ok(o) => {
            let stdout = String::from_utf8_lossy(&o.stdout);
            stdout.lines().any(|line| line.contains("libvpx-vp9"))
        }
        Err(_) => false,
    }
}

/// Probe whether the current ffmpeg binary has the `libopus` encoder compiled in.
///
/// Required for audio encoding during MP4→WebM and WebM/AV1→WebM/VP9 transcoding.
/// Runs `ffmpeg -encoders` and scans stdout for a line containing `libopus`.
/// Returns `true` only when ffmpeg is present AND the encoder is available.
///
/// This is a synchronous, blocking call intended for use at server startup.
#[must_use]
pub fn check_opus_encoder() -> bool {
    let output = Command::new("ffmpeg")
        .args(["-encoders"])
        .stdout(Stdio::piped())
        .stderr(Stdio::null())
        .output();

    match output {
        Ok(o) => {
            let stdout = String::from_utf8_lossy(&o.stdout);
            stdout.lines().any(|line| line.contains("libopus"))
        }
        Err(_) => false,
    }
}
